//! The raw door's census: what a shipped build can and cannot mint.
//!
//! [`profile::RawLoop`] is a fixture door behind
//! `#[cfg(any(test, feature = "test-support"))]`, and the claim that
//! buys is a claim about a build nobody here runs: the one a downstream
//! crate makes with `cargo build [--release]`, where no dev-dependency
//! edge exists to turn the feature on. Three rows stand under that
//! claim, and only the first of them is a compiler's answer.
//!
//! 1. [`a_shipped_build_cannot_mint_a_vertex_table`] COMPILES a
//!    downstream crate — a real one, with a real dependency edge — and
//!    reads what rustc says. The negative arm is the claim; the
//!    positive arm is the control that keeps the negative from passing
//!    for the wrong reason (a typo in the witness source would fail
//!    both).
//! 2. [`no_production_source_writes_a_vertex_table`] is the census of
//!    the tree as it stands: the writers this crate's own emission
//!    layer and [`profile::ProfileLoop::embed`] do not account for are
//!    all inside `#[cfg(test)]` modules or test targets.
//! 3. [`the_door_carries_its_gate`] reads the door itself, so a future
//!    edit that widens the gate fails here rather than silently
//!    restoring the tier.
//!
//! `crates/pncad`'s `every_profile_layer_root_export_is_carried_or_listed`
//! is the fourth, from the façade's side: `RawLoop` is not in this
//! layer's shipped root export set at all any more, which is why that
//! guard's interior list is empty.
//!
//! `scripts/gates/test-features-dev-only.sh` covers the manifests —
//! no non-dev edge in the repository turns `test-support` on — so that
//! question is not re-asked here.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::process::Command;

/// The repository root, from this crate's manifest directory.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("the repository root resolves from crates/profile")
}

/// Writes the witness crate and runs `cargo check` on it, returning
/// rustc's combined output and whether it succeeded.
///
/// The witness lives under the repository's own `target/` — ignored by
/// git, and INSIDE the tree so that `rust-toolchain.toml` applies to
/// the nested invocation (outside it, cargo picks the default toolchain
/// and refuses on `rust-version` before it ever reaches the door). Its
/// lockfile is the workspace's, copied, so `--offline` resolves from
/// the cache the outer build already filled rather than reaching for an
/// index.
fn check_witness(with_test_support: bool) -> (bool, String) {
    let root = repo_root();
    let dir = root.join("target").join(if with_test_support {
        "raw-door-witness-open"
    } else {
        "raw-door-witness-shut"
    });
    std::fs::create_dir_all(dir.join("src")).expect("the witness directory is writable");
    let features = if with_test_support {
        r#", features = ["test-support"]"#
    } else {
        ""
    };
    std::fs::write(
        dir.join("Cargo.toml"),
        format!(
            "# GENERATED by profile's raw_door_census suite; rewritten on every run.\n\
             [workspace]\n\n\
             [package]\n\
             name = \"raw-door-witness\"\n\
             version = \"0.0.0\"\n\
             edition = \"2024\"\n\
             publish = false\n\n\
             [dependencies]\n\
             profile = {{ path = \"{}\"{features} }}\n",
            root.join("crates/profile").display(),
        ),
    )
    .expect("the witness manifest is writable");
    std::fs::write(
        dir.join("src/lib.rs"),
        "use profile::RawLoop;\n\
         pub fn mint() -> profile::ProfileLoop<f64> {\n    \
             RawLoop::new(Vec::new())\n\
         }\n",
    )
    .expect("the witness source is writable");
    std::fs::copy(root.join("Cargo.lock"), dir.join("Cargo.lock"))
        .expect("the workspace lockfile is readable");

    let out = Command::new(std::env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .arg("check")
        .arg("--offline")
        .current_dir(&dir)
        .env("CARGO_TARGET_DIR", dir.join("target"))
        // The outer run's flags are not the witness's subject; a
        // `-D warnings` inherited from CI would turn an unrelated lint
        // into this row's answer.
        .env_remove("RUSTFLAGS")
        .output()
        .expect("cargo runs");
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    (out.status.success(), text)
}

/// **The enforcement, executed.** A downstream crate that names the raw
/// door in a shipped build does not compile; the same crate with the
/// dev feature on does.
///
/// The negative arm asserts on the ERROR KIND, not on a message: E0603
/// is "this item is private", which is the precise fact — the name
/// still exists (the emission layer calls it), and what a shipped build
/// lacks is reach.
#[test]
fn a_shipped_build_cannot_mint_a_vertex_table() {
    let (ok, text) = check_witness(false);
    assert!(
        !ok,
        "a shipped build minted a vertex table through `RawLoop` — the \
         gate on the door is open:\n{text}"
    );
    assert!(
        text.contains("E0603") && text.contains("RawLoop"),
        "the shipped build failed, but not on the door — expected E0603 \
         on `RawLoop`:\n{text}"
    );

    let (ok, text) = check_witness(true);
    assert!(
        ok,
        "the control arm failed: with `test-support` on, the witness \
         must compile, or the row above proved a typo rather than a \
         gate:\n{text}"
    );
}

/// The attributes attached to line `i`: the run of `#[…]` lines
/// immediately above it.
fn attributes_above(lines: &[&str], i: usize) -> String {
    let mut out = String::new();
    let mut k = i;
    while k > 0 && lines[k - 1].trim_start().starts_with("#[") {
        k -= 1;
        out.push_str(lines[k].trim());
    }
    out
}

/// Does this attribute run gate on a test cfg? `#[cfg(test)]` and
/// `#[cfg(any(test, feature = "test-support"))]` both count; the
/// question is whether a shipped build compiles what follows.
fn gates_on_test(attrs: &str) -> bool {
    attrs.contains("cfg(") && attrs.contains("test")
}

/// Where a file's in-file test region begins — the first `mod` block
/// carrying a test cfg — or `usize::MAX` if it has none.
///
/// Deliberately coarse: the region runs to the end of the file. Every
/// hit in this tree is in a trailing test module, and a rule that
/// OVER-counts test regions can only make this census miss a writer,
/// never invent one; [`a_shipped_build_cannot_mint_a_vertex_table`] is
/// what makes a miss survivable.
fn test_module_starts_at(src: &str) -> usize {
    let lines: Vec<&str> = src.lines().collect();
    lines
        .iter()
        .enumerate()
        .find_map(|(i, l)| {
            let t = l.trim_start();
            let is_mod = t.starts_with("mod ")
                || t.starts_with("pub mod ")
                || t.starts_with("pub(crate) mod ");
            (is_mod && !t.ends_with(';') && gates_on_test(&attributes_above(&lines, i)))
                .then_some(i)
        })
        .unwrap_or(usize::MAX)
}

/// The FILE modules a source declares behind a test cfg (`#[cfg(any(test,
/// feature = "test-support"))] pub mod test_support;`).
///
/// A file gated at its declaration is not production source at all, and
/// the gate is one file away from the code it covers — which is why
/// this is resolved rather than allow-listed. `sweep::test_support` is
/// the live instance; the resolution is general.
fn gated_module_files(file: &Path, src: &str, out: &mut Vec<PathBuf>) {
    let dir = match file.file_name().and_then(|n| n.to_str()) {
        Some("lib.rs") | Some("main.rs") | Some("mod.rs") => file.parent().map(Path::to_path_buf),
        _ => file.parent().map(|p| {
            p.join(
                file.file_stem()
                    .and_then(|n| n.to_str())
                    .unwrap_or_default(),
            )
        }),
    };
    let Some(dir) = dir else { return };
    let lines: Vec<&str> = src.lines().collect();
    for (i, line) in lines.iter().enumerate() {
        let t = line.trim();
        let Some(rest) = t
            .strip_prefix("pub mod ")
            .or_else(|| t.strip_prefix("pub(crate) mod "))
            .or_else(|| t.strip_prefix("mod "))
        else {
            continue;
        };
        let Some(name) = rest.strip_suffix(';') else {
            continue;
        };
        if !gates_on_test(&attributes_above(&lines, i)) {
            continue;
        }
        out.push(dir.join(format!("{name}.rs")));
        out.push(dir.join(name));
    }
}

fn is_writer(line: &str) -> bool {
    let squashed: String = line.chars().filter(|c| !c.is_whitespace()).collect();
    [
        "RawLoop::new(",
        "RawLoop::polygon(",
        "ProfileLoop::new(",
        "ProfileLoop::polygon(",
        ".with_tangent_joints(",
    ]
    .iter()
    .any(|m| squashed.contains(m))
}

/// Every `src/` file in the repository, outside this crate.
fn production_sources(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    for area in ["crates", "demos", "tools"] {
        let Ok(entries) = std::fs::read_dir(root.join(area)) else {
            continue;
        };
        for entry in entries.flatten() {
            let src = entry.path().join("src");
            if entry.file_name() == "profile" && area == "crates" {
                continue;
            }
            walk(&src, &mut out);
        }
    }
    out.sort();
    out
}

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let p = entry.path();
        if p.is_dir() {
            walk(&p, out);
        } else if p.extension().is_some_and(|e| e == "rs") {
            out.push(p);
        }
    }
}

/// **The tree as it stands**: no production source writes a vertex
/// table.
///
/// The scan is over `src/` only. `tests/`, `examples/` and `benches/`
/// are test targets — the door's whole population, and the reason it
/// still exists — so scanning them would be asking the wrong question.
#[test]
fn no_production_source_writes_a_vertex_table() {
    let root = repo_root();
    let files = production_sources(&root);
    assert!(
        files.len() > 100,
        "the scanner found only {} source files — the tree's shape \
         changed and this census was about to pass vacuously",
        files.len()
    );

    let sources: Vec<(PathBuf, String)> = files
        .iter()
        .map(|f| {
            (
                f.clone(),
                std::fs::read_to_string(f).expect("a source file reads"),
            )
        })
        .collect();
    let mut gated = Vec::new();
    for (file, src) in &sources {
        gated_module_files(file, src, &mut gated);
    }

    let mut hits = Vec::new();
    for (file, src) in &sources {
        if gated.iter().any(|g| file.starts_with(g) || file == g) {
            continue;
        }
        let cut = test_module_starts_at(src);
        for (n, line) in src.lines().enumerate() {
            if n < cut && !line.trim_start().starts_with("//") && is_writer(line) {
                hits.push(format!(
                    "{}:{}: {}",
                    file.strip_prefix(&root).unwrap_or(file).display(),
                    n + 1,
                    line.trim()
                ));
            }
        }
    }
    assert!(
        hits.is_empty(),
        "production source writes a vertex table by hand — author \
         through the `path` lattice, or, for a table that already \
         exists in another scalar, `ProfileLoop::embed`:\n  {}",
        hits.join("\n  ")
    );
}

/// **The gate on the door**, read from the source that declares it: the
/// trait is interior, and its two re-exports are the arms.
///
/// A widening edit — dropping the `cfg`, or promoting the narrow arm to
/// `pub` — fails here. The compile row above would catch it too, at
/// four seconds; this one names it in one.
#[test]
fn the_door_carries_its_gate() {
    let src = std::fs::read_to_string(repo_root().join("crates/profile/src/lib.rs"))
        .expect("profile's lib.rs reads");
    let gate = r#"#[cfg(any(test, feature = "test-support"))]"#;
    let wide = format!("{gate}\npub use raw_loop::RawLoop;");
    let narrow =
        "#[cfg(not(any(test, feature = \"test-support\")))]\npub(crate) use raw_loop::RawLoop;";
    assert!(
        src.contains(&wide),
        "the raw door's OPEN arm is not the gated `pub use` this census \
         reads — if the spelling moved, move this row with it"
    );
    assert!(
        src.contains(narrow),
        "the raw door's SHUT arm is not the `pub(crate) use` this census \
         reads — a narrow arm spelled `pub` would put the minting tier \
         back on every shipped build's surface"
    );
    assert!(
        !src.contains("\npub trait RawLoop"),
        "`RawLoop` is declared at the crate root again — a root `pub \
         trait` is exported unconditionally, which is the gate gone"
    );
}
