//! R1 adversarial review probes for PR #252 (M7-5 band seam re-mint).
//!
//! C2: seam correctness at rest on the two flipped wild fixtures, and
//! doctored off-azimuth attacks. C3: the D2 torus adjudication by
//! construction — synthetic two-band solids (torus band + cylinder
//! band glued along two shared seamless rims) and one-band washer
//! solids whose winding x sense encodings select the torus v-region,
//! state it inside-out, or invert the cylinder. Fixtures generated by
//! the reviewer's `gen_fixtures*.py`; set `R1_PROBE_DIR` to their
//! directory to run those probes.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use std::collections::BTreeMap;

use common::census;
use step_import::{ImportOptions, StepImport, import_step};

fn wild(rel: &str) -> String {
    let p = format!("{}/tests/fixtures/wild/{rel}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(p).unwrap()
}

fn probe(name: &str) -> Option<String> {
    let dir = std::env::var("R1_PROBE_DIR").ok()?;
    Some(std::fs::read_to_string(format!("{dir}/{name}")).unwrap())
}

/// Every `EdgeGeometry::Seam` edge of the body: (both half-edges'
/// faces, endpoint positions).
#[allow(clippy::type_complexity)]
fn seam_edges(
    body: &topo::Body<f64>,
) -> Vec<(topo::FaceKey, topo::FaceKey, [geom_core::Point3<f64>; 2])> {
    let mut loop_face = BTreeMap::new();
    for (fk, f) in body.faces() {
        loop_face.insert(f.outer, fk);
        for r in &f.rings {
            loop_face.insert(*r, fk);
        }
    }
    let mut out = Vec::new();
    for (_, e) in body.edges() {
        let Some(topo::CurveGeom::Certified(c)) = body.get_curve_geom(e.curve) else {
            continue;
        };
        if !matches!(*c.description(), geom_brep::EdgeGeometry::Seam { .. }) {
            continue;
        }
        let hp = body.get_half_edge(e.he_plus).unwrap();
        let hm = body.get_half_edge(e.he_minus).unwrap();
        let pt = |vk| *body.get_point(body.get_vertex(vk).unwrap().point).unwrap();
        out.push((
            loop_face[&hp.parent_loop],
            loop_face[&hm.parent_loop],
            [pt(hp.start), pt(hm.start)],
        ));
    }
    out
}

/// C2 at rest: the two flipped fixtures' minted seams are
/// `EdgeGeometry::Seam`, both half-edges on ONE face, and every seam
/// endpoint lies in the surface's u_ref half-plane (positions derived
/// by the reviewer from the raw STEP entities, in kernel metres).
#[test]
fn r1_seams_at_rest_on_both_fixtures() {
    let rows: [(&str, usize, &[([f64; 3], [f64; 3], [f64; 3])]); 2] = [
        (
            "occ-oss/cq_red_cube_blue_cylinder.step",
            1,
            &[([0.01, 0.005, 0.0], [0.0, 0.0, 1.0], [-1.0, 0.0, 0.0])],
        ),
        (
            "nist/nist_ftc_11_asme1_rb.stp",
            4,
            &[
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, -1.0, 0.0]),
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, -1.0, 0.0]),
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]),
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]),
            ],
        ),
    ];
    for (name, n, surfs) in rows {
        let Ok(StepImport::Solid { body, .. }) = import_step(&wild(name), &ImportOptions::default())
        else {
            panic!("{name}: imports first-class");
        };
        let seams = seam_edges(&body);
        assert_eq!(seams.len(), n, "{name}: seam edge count");
        for (fp, fm, pts) in &seams {
            assert_eq!(fp, fm, "{name}: both seam half-edges on ONE face");
            for p in pts {
                let ok = surfs.iter().any(|(loc, axis, uref)| {
                    let d = [p.x - loc[0], p.y - loc[1], p.z - loc[2]];
                    let y = [
                        axis[1] * uref[2] - axis[2] * uref[1],
                        axis[2] * uref[0] - axis[0] * uref[2],
                        axis[0] * uref[1] - axis[1] * uref[0],
                    ];
                    let off = d[0] * y[0] + d[1] * y[1] + d[2] * y[2];
                    let along = d[0] * uref[0] + d[1] * uref[1] + d[2] * uref[2];
                    off.abs() < 1e-15 && along >= 0.0
                });
                assert!(ok, "{name}: seam endpoint {p:?} not in a u_ref half-plane");
            }
        }
    }
}

/// C3(a): the torus winding x sense pair SELECTS the v-region. Two
/// files, identical surfaces and rims (vertex azimuth 180 deg — clear
/// of the wrap-misread window and leaving readable half-turn arcs
/// after splits), differing only in encodings: A states the outer
/// torus half, B the inner. Both must import first-class to
/// DIFFERENT, closed-form-correct volumes. The washer control (one
/// torus band + two discs) pins the same read on an unshared rim.
#[test]
fn r1_torus_region_selection_is_real() {
    let Some(a) = probe("band_a180.stp") else {
        eprintln!("R1_PROBE_DIR unset: skipping");
        return;
    };
    let pi = std::f64::consts::PI;
    let rows = [
        (a, "A/outer", (40.0 * pi * pi + 32.0 * pi / 3.0) * 1e-9, (1, 1, 2, 6, 4), 2),
        (
            probe("band_b180.stp").unwrap(),
            "B/inner",
            (40.0 * pi * pi - 32.0 * pi / 3.0) * 1e-9,
            (1, 1, 2, 6, 4),
            2,
        ),
        (
            probe("washer180.stp").unwrap(),
            "washer/control",
            (400.0 * pi + 40.0 * pi * pi + 32.0 * pi / 3.0) * 1e-9,
            (1, 1, 3, 5, 4),
            1,
        ),
    ];
    for (text, tag, v_want, cens, n_seams) in rows {
        let Ok(StepImport::Solid { body, .. }) = import_step(&text, &ImportOptions::default())
        else {
            panic!(
                "{tag}: the band probe solid imports first-class, got {:?}",
                import_step(&text, &ImportOptions::default()).err()
            );
        };
        assert_eq!(census(&body), cens, "{tag}: census");
        let v = topo::mass_properties(&body).unwrap().volume;
        let rel = ((v - v_want) / v_want).abs();
        assert!(
            rel < 1e-12,
            "{tag}: volume {v:e} vs closed form {v_want:e} (rel {rel:e})"
        );
        assert_eq!(seam_edges(&body).len(), n_seams, "{tag}: seam count");
    }
}

/// C3(b): the inside-out torus band (faces consistently stating the
/// complement region with inverted senses) must refuse LOUDLY — never
/// import certify-green.
#[test]
fn r1_inside_out_torus_band_never_imports_green() {
    let Some(c) = probe("band_c180.stp") else {
        eprintln!("R1_PROBE_DIR unset: skipping");
        return;
    };
    match import_step(&c, &ImportOptions::default()) {
        Err(e) => eprintln!("inside-out band refused: {e}"),
        Ok(StepImport::Solid { body, .. }) => {
            let mp = topo::mass_properties(&body);
            panic!(
                "inside-out torus band imported GREEN: census {:?}, volume {:?}",
                census(&body),
                mp.map(|m| m.volume)
            );
        }
        Ok(_) => panic!("wireframe?"),
    }
}

/// C3(c): the inverted CYLINDER band refuses typed pre-body, as D2
/// ruled and the mint claims (cylinder listed first in the shell so
/// its mint runs first; vertex azimuth 180 keeps the winding read off
/// the wrap).
#[test]
fn r1_inverted_cylinder_band_refuses_pre_body() {
    let Some(d) = probe("band_d180.stp") else {
        eprintln!("R1_PROBE_DIR unset: skipping");
        return;
    };
    let e = import_step(&d, &ImportOptions::default()).unwrap_err();
    let msg = e.to_string();
    eprintln!("d180: {msg}");
    assert!(
        msg.contains("ORIENTATION-INVERTED cylinder band"),
        "expected the typed pre-body inversion refusal, got: {msg}"
    );
}

/// DEFECT PROBE 1 (found in round 1): a coherent two-band solid whose
/// bands share BOTH rims refuses winding-undecidable — the second
/// band's mint reads `uses[0]` of a rim the FIRST band's mint already
/// split, and `chart_direction`'s 5%-of-span step on a quarter-turn
/// arc is below its 0.1 rad floor. Round-1 fixtures (vertex azimuth
/// 90) demonstrate; this pins the refusal so the report can quote it.
#[test]
fn r1_defect_shared_rim_split_starves_second_band_winding() {
    let Some(a) = probe("band_a.stp") else {
        eprintln!("R1_PROBE_DIR unset: skipping");
        return;
    };
    match import_step(&a, &ImportOptions::default()) {
        Err(e) => eprintln!("coherent 90-deg two-band solid REFUSED: {e}"),
        Ok(StepImport::Solid { body, .. }) => {
            let v = topo::mass_properties(&body).map(|m| m.volume);
            eprintln!(
                "90-deg two-band solid imported: census {:?} volume {:?}",
                census(&body),
                v
            );
        }
        Ok(_) => panic!("wireframe?"),
    }
}

/// DEFECT PROBE 2: `chart_direction`'s samples (25% and 30% of the rim
/// interval) straddle the u = pi wrap when the rim's vertex sits in
/// (0.4 pi, 0.5 pi] azimuth — the finite difference reads the true
/// direction INVERTED. On a one-band washer the misread flips the
/// decoded v-region of the torus. This probe reports what the import
/// does with it: a certify-green import must at least have the
/// CORRECT volume (the control's closed form); a green import with a
/// different volume is silent wrong geometry.
#[test]
fn r1_defect_wrap_misread_on_washer90() {
    let Some(w) = probe("washer90.stp") else {
        eprintln!("R1_PROBE_DIR unset: skipping");
        return;
    };
    let pi = std::f64::consts::PI;
    let v_true = (400.0 * pi + 40.0 * pi * pi + 32.0 * pi / 3.0) * 1e-9;
    match import_step(&w, &ImportOptions::default()) {
        Err(e) => eprintln!("washer90 refused: {e}"),
        Ok(StepImport::Solid { body, .. }) => {
            let v = topo::mass_properties(&body).map(|m| m.volume);
            eprintln!(
                "washer90 imported: census {:?} volume {v:?} (true {v_true:e})",
                census(&body)
            );
            let v = v.unwrap();
            assert!(
                ((v - v_true) / v_true).abs() < 1e-12,
                "washer90 imported GREEN with the WRONG volume: {v:e} vs true {v_true:e} \
                 — the wrap-misread minted the complement region silently"
            );
        }
        Ok(_) => panic!("wireframe?"),
    }
}

/// C2 attack: rim vertices doctored off the u_ref azimuth (see round-1
/// findings in the report; `uref_off` demonstrates the Seam->
/// MappedCurve adoption fallback absorbing an off-halfplane seam).
#[test]
fn r1_off_azimuth_vertex_attack() {
    for (name, off) in [
        ("ftc11_voff_tiny.stp", 1e-10),
        ("ftc11_voff_mid.stp", 1.6e-6),
        ("ftc11_uref_off.stp", 1.6e-6),
    ] {
        let Some(text) = probe(name) else {
            eprintln!("R1_PROBE_DIR unset: skipping");
            return;
        };
        match import_step(&text, &ImportOptions::default()) {
            Err(e) => eprintln!("{name} (off {off:e} m): refused: {e}"),
            Ok(StepImport::Solid { body, .. }) => {
                let seams = seam_edges(&body);
                eprintln!(
                    "{name} (off {off:e} m): imported GREEN, {} Seam edges, census {:?}",
                    seams.len(),
                    census(&body)
                );
                for (_, _, pts) in &seams {
                    eprintln!("  seam endpoints {pts:?}");
                }
            }
            Ok(_) => panic!("wireframe?"),
        }
    }
}
