//! R1 adversarial review probes for PR #252 (M7-5 band seam re-mint),
//! adopted as PERMANENT rows at the fix pass.
//!
//! C2: seam correctness at rest on the two flipped wild fixtures.
//! C3: the D2 torus adjudication by construction — synthetic two-band
//! solids (torus band + cylinder band glued along two shared seamless
//! rims) and one-band washer solids whose winding x sense encodings
//! select the torus v-region, state it inside-out, or invert the
//! cylinder. Fixtures generated by the reviewer's `gen_fixtures*.py`
//! (review/r1-band-seam/) and committed under `tests/fixtures/band/`;
//! closed-form volumes are the fixtures' own ground truth. The two
//! defect probes of the review (wrap-misread, split starvation) are
//! now the PINS of their fixes: the structural winding read and the
//! tier-3 gate that actually runs on every imported solid.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use crate::common;

use std::collections::BTreeMap;

use common::census;
use geom_core::Tol;
use step_import::{ImportOptions, StepImport, import_step};

fn wild(rel: &str) -> String {
    let p = format!("{}/tests/fixtures/wild/{rel}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(p).unwrap()
}

fn band(name: &str) -> String {
    let p = format!("{}/tests/fixtures/band/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(p).unwrap()
}

/// Every the seam chart image edge of the body: (both half-edges'
/// faces, endpoint positions).
#[allow(clippy::type_complexity)]
fn seam_edges(
    body: &topo::Body<f64>,
) -> Vec<(topo::FaceKey, topo::FaceKey, [geom_core::Point3<f64>; 2])> {
    let mut loop_face = BTreeMap::new();
    for (fk, f) in body.faces() {
        loop_face.insert(f.outer, fk);
        for r in &f.rings {
            loop_face.insert(*r, fk);
        }
    }
    let mut out = Vec::new();
    for (_, e) in body.edges() {
        let Some(topo::CurveGeom::Certified(c)) = body.get_curve_geom(e.curve) else {
            continue;
        };
        if !matches!(c.description(), geom_brep::EdgeDescription::Chart(cc) if cc.seam) {
            continue;
        }
        let hp = body.get_half_edge(e.he_plus).unwrap();
        let hm = body.get_half_edge(e.he_minus).unwrap();
        let pt = |vk| *body.get_point(body.get_vertex(vk).unwrap().point).unwrap();
        out.push((
            loop_face[&hp.parent_loop],
            loop_face[&hm.parent_loop],
            [pt(hp.start), pt(hm.start)],
        ));
    }
    out
}

/// C2 at rest: the two flipped fixtures' minted seams are
/// the seam chart image, both half-edges on ONE face, and every seam
/// endpoint lies in the surface's u_ref half-plane (positions derived
/// by the reviewer from the raw STEP entities, in kernel metres).
/// One surface's u_ref half-plane, as raw triples: (a point on the
/// axis, the axis direction, the u_ref direction).
type HalfPlane = ([f64; 3], [f64; 3], [f64; 3]);

#[test]
fn r1_seams_at_rest_on_both_fixtures() {
    let rows: [(&str, usize, &[HalfPlane]); 2] = [
        (
            "occ-oss/cq_red_cube_blue_cylinder.step",
            1,
            &[([0.01, 0.005, 0.0], [0.0, 0.0, 1.0], [-1.0, 0.0, 0.0])],
        ),
        (
            "nist/nist_ftc_11_asme1_rb.stp",
            4,
            &[
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, -1.0, 0.0]),
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, -1.0, 0.0]),
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]),
                ([0.0, 0.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0]),
            ],
        ),
    ];
    for (name, n, surfs) in rows {
        let Ok(StepImport::Solid { body, .. }) =
            import_step(&wild(name), &ImportOptions::default(), Tol::witness())
        else {
            panic!("{name}: imports first-class");
        };
        let seams = seam_edges(&body);
        assert_eq!(seams.len(), n, "{name}: seam edge count");
        for (fp, fm, pts) in &seams {
            assert_eq!(fp, fm, "{name}: both seam half-edges on ONE face");
            for p in pts {
                let ok = surfs.iter().any(|(loc, axis, uref)| {
                    let d = [p.x - loc[0], p.y - loc[1], p.z - loc[2]];
                    let y = [
                        axis[1] * uref[2] - axis[2] * uref[1],
                        axis[2] * uref[0] - axis[0] * uref[2],
                        axis[0] * uref[1] - axis[1] * uref[0],
                    ];
                    let off = d[0] * y[0] + d[1] * y[1] + d[2] * y[2];
                    let along = d[0] * uref[0] + d[1] * uref[1] + d[2] * uref[2];
                    off.abs() < 1e-15 && along >= 0.0
                });
                assert!(ok, "{name}: seam endpoint {p:?} not in a u_ref half-plane");
            }
        }
    }
}

/// C3(a): the torus winding x sense pair SELECTS the v-region. Two
/// files, identical surfaces and rims (vertex azimuth 180 deg — clear
/// of the wrap-misread window and leaving readable half-turn arcs
/// after splits), differing only in encodings: A states the outer
/// torus half, B the inner. Both must import first-class to
/// DIFFERENT, closed-form-correct volumes. The washer control (one
/// torus band + two discs) pins the same read on an unshared rim.
#[test]
fn r1_torus_region_selection_is_real() {
    let pi = std::f64::consts::PI;
    let rows = [
        (
            band("band_a180.stp"),
            "A/outer",
            (40.0 * pi * pi + 32.0 * pi / 3.0) * 1e-9,
            (1, 1, 2, 6, 4),
            2,
        ),
        (
            band("band_b180.stp"),
            "B/inner",
            (40.0 * pi * pi - 32.0 * pi / 3.0) * 1e-9,
            (1, 1, 2, 6, 4),
            2,
        ),
        (
            band("washer180.stp"),
            "washer/control",
            (400.0 * pi + 40.0 * pi * pi + 32.0 * pi / 3.0) * 1e-9,
            (1, 1, 3, 5, 4),
            1,
        ),
    ];
    for (text, tag, v_want, cens, n_seams) in rows {
        let Ok(StepImport::Solid { body, .. }) =
            import_step(&text, &ImportOptions::default(), Tol::witness())
        else {
            panic!(
                "{tag}: the band probe solid imports first-class, got {:?}",
                import_step(&text, &ImportOptions::default(), Tol::witness()).err()
            );
        };
        assert_eq!(census(&body), cens, "{tag}: census");
        let v = topo::mass_properties(&body, Tol::witness()).unwrap().volume;
        let rel = ((v - v_want) / v_want).abs();
        assert!(
            rel < 1e-12,
            "{tag}: volume {v:e} vs closed form {v_want:e} (rel {rel:e})"
        );
        assert_eq!(seam_edges(&body).len(), n_seams, "{tag}: seam count");
    }
}

/// C3(b): the inside-out torus band (faces consistently stating the
/// complement region with inverted senses) REFUSES at import — the
/// kernel's tier-3 gates are the D2 region decode's documented
/// backstop, and they RUN before the body ships, so the
/// negative-volume body never imports green.
///
/// The mechanism is the general one (#260 ruling (a)): this fixture
/// refuses through the shared at-rest gate EVERY imported solid
/// passes, with no band-specific validation anywhere on the path. A
/// band is not a special kind of body; it is an ordinary body whose
/// region decode happens to lean on gates the whole corpus now runs.
#[test]
fn r1_inside_out_torus_band_never_imports_green() {
    let e = import_step(
        &band("band_c180.stp"),
        &ImportOptions::default(),
        Tol::witness(),
    )
    .unwrap_err();
    assert!(
        matches!(
            &e,
            step_import::StepImportError::TierInvalid { solid: None, errors }
                if matches!(errors.as_slice(), [topo::ValidationError::NegativeVolume])
        ),
        "expected the shared gate's typed refusal on the +V invariant, got: {e:?}"
    );
    let msg = e.to_string();
    assert!(
        msg.contains("shared at-rest validation gate") && msg.contains("NegativeVolume"),
        "the message names the gate and the failing check: {msg}"
    );
}

/// C3(c): the inverted CYLINDER band refuses typed pre-body, as D2
/// ruled — at BOTH vertex azimuths: 180 (always read correctly) and
/// 90, the azimuth that neutralized the sampled winding read before
/// the structural read replaced it (R1 fix pass, MAJ-2/MAJ-3's pin —
/// deleting the refusal or re-breaking the read turns this row red).
#[test]
fn r1_inverted_cylinder_band_refuses_pre_body() {
    for name in ["band_d180.stp", "band_d_invcyl.stp"] {
        let e = import_step(&band(name), &ImportOptions::default(), Tol::witness()).unwrap_err();
        let msg = e.to_string();
        assert!(
            msg.contains("ORIENTATION-INVERTED cylinder band"),
            "{name}: expected the typed pre-body inversion refusal, got: {msg}"
        );
    }
}

/// DEFECT PROBE 1, now the fix's pin (R1 fix pass, m1): a coherent
/// two-band solid sharing BOTH rims imports first-class REGARDLESS of
/// mint order. The torus band is listed first, so its mint splits the
/// shared rims before the cylinder band reads its winding — the old
/// sampled read starved on the leftover quarter-turn arc and refused
/// a valid solid; the structural read does not sample.
#[test]
fn r1_shared_rim_split_order_does_not_starve_the_second_band() {
    let pi = std::f64::consts::PI;
    let v_want = (40.0 * pi * pi + 32.0 * pi / 3.0) * 1e-9;
    let Ok(StepImport::Solid { body, .. }) = import_step(
        &band("band_a.stp"),
        &ImportOptions::default(),
        Tol::witness(),
    ) else {
        panic!(
            "band_a (vertex azimuth 90, torus minted first): {:?}",
            import_step(
                &band("band_a.stp"),
                &ImportOptions::default(),
                Tol::witness()
            )
            .err()
        );
    };
    assert_eq!(census(&body), (1, 1, 2, 6, 4), "band_a census");
    let v = topo::mass_properties(&body, Tol::witness()).unwrap().volume;
    assert!(
        ((v - v_want) / v_want).abs() < 1e-12,
        "band_a volume {v:e} vs closed form {v_want:e}"
    );
    assert_eq!(seam_edges(&body).len(), 2, "band_a seam count");
}

/// DEFECT PROBE 2, now the fix's pin (R1 fix pass, MAJ-2): the washer
/// whose rim vertex sits at azimuth 90 deg — inside the old sampled
/// read's wrap-misread window, where the mint silently produced the
/// COMPLEMENT region (inner half, wrong volume, green import). With
/// the structural winding read it must import to the same closed form
/// as the 180-deg control.
#[test]
fn r1_washer90_imports_the_true_region() {
    let pi = std::f64::consts::PI;
    let v_true = (400.0 * pi + 40.0 * pi * pi + 32.0 * pi / 3.0) * 1e-9;
    let Ok(StepImport::Solid { body, .. }) = import_step(
        &band("washer90.stp"),
        &ImportOptions::default(),
        Tol::witness(),
    ) else {
        panic!(
            "washer90: {:?}",
            import_step(
                &band("washer90.stp"),
                &ImportOptions::default(),
                Tol::witness()
            )
            .err()
        );
    };
    assert_eq!(census(&body), (1, 1, 3, 5, 4), "washer90 census");
    assert_eq!(
        topo::validate_geometric(&body, Tol::witness()),
        Ok(()),
        "washer90 tier 3"
    );
    let v = topo::mass_properties(&body, Tol::witness()).unwrap().volume;
    assert!(
        ((v - v_true) / v_true).abs() < 1e-12,
        "washer90 volume {v:e} vs true {v_true:e} — the winding read regressed"
    );
    assert_eq!(seam_edges(&body).len(), 1, "washer90 seam count");
}

/// C2 attack, now the fix's pin (R1 fix pass, m2): a band whose
/// surface u_ref is rotated 1e-4 rad leaves the rim vertices 1.6e-6 m
/// off the seam azimuth — inside the mint's ε_in vertex budget
/// (1e-5 m), outside ambient certification. The minted generator is
/// D1's spatial statement of the u_ref half-plane, so adoption offers
/// it ONLY as the seam chart image: certification fails and the
/// import refuses typed with the ladder's own report — never the old
/// silent MappedCurve downgrade that imported green with 3 of 4
/// seams.
#[test]
fn r1_off_uref_band_refuses_rather_than_downgrading_its_seam() {
    let e = import_step(
        &band("ftc11_uref_off.stp"),
        &ImportOptions::default(),
        Tol::witness(),
    )
    .unwrap_err();
    let msg = e.to_string();
    assert!(
        msg.contains("no intensional description certifies") && msg.contains("seam"),
        "expected the seam-only adoption refusal, got: {msg}"
    );
}
