//! **Issue #653, the import route.** A cylindrical face whose vertical
//! boundary the FILE states as two collinear `EDGE_CURVE`s — which is
//! what every exporter emits the moment a vertex lands on that edge —
//! placed obliquely, imported, and tessellated.
//!
//! This is the half of #653 that needs no kernel mutator at all.
//! `crates/mesh`'s own row (`curved::tests::
//! a_multiply_carried_iso_side_is_bitwise_straight_and_meshes_watertight`)
//! reaches the same shape through `topo::Body::split_edge`, where the
//! two sub-edges share one carrier; here they are two SEPARATE
//! `LINE`s, adopted independently, so nothing about carrier identity
//! is available to the walk. Before the fix each derived its own
//! column from its own `mid_azimuth` point and the mesh came back
//! `Ok` and **not watertight**:
//!
//! ```text
//!                       main                        with #653's fix
//! plain_axis.step       16 tris  CLEAN              16 tris  CLEAN
//! split_axis.step       18 tris  CLEAN              18 tris  CLEAN
//! plain_oblique.step    16 tris  CLEAN              16 tris  CLEAN
//! split_oblique.step    19 tris  DIRTY  <-- here    18 tris  CLEAN
//! ```
//!
//! The axis-aligned split is clean on main for the reason the issue
//! names and no other: on an axis-aligned dyadic placement the two
//! `atan2`s land on the same bits by luck. The oblique one is the same
//! part.
//!
//! The four files are generated by `fixtures/split-iso/generate.py`
//! (`python3 generate.py <dir>`); they are hand-authored AP214, ~5 kB
//! each, and are committed rather than generated at test time so the
//! row does not depend on a Python interpreter.

#![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]

use mesh::tessellate;
use mesh::validate::check_mesh;
use step_import::{ImportOptions, StepImport, import_step};
use geom_core::Tol;

fn fixture(name: &str) -> String {
    let p = format!(
        "{}/tests/fixtures/split-iso/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::read_to_string(p).unwrap()
}

/// One fixture's two δ rows: triangle count and validator verdict each.
type Rows = Vec<(usize, Result<(), String>)>;

/// Imports one fixture and tessellates it at two δ, returning the
/// triangle count and the validator's verdict for each.
fn meshed(name: &str) -> Rows {
    let imported = import_step(&fixture(name), &ImportOptions::default())
        .unwrap_or_else(|e| panic!("{name} must import: {e:?}"));
    let StepImport::Solid { body, .. } = imported else {
        panic!("{name} must import as a solid");
    };
    [2.0e-3, 5.0e-4]
        .into_iter()
        .map(|d| {
            let m = tessellate(&body, d, Tol::witness()).unwrap_or_else(|e| panic!("{name} at δ={d}: {e:?}"));
            let n: usize = m.patches.iter().map(|p| p.triangles.len()).sum();
            (n, check_mesh(&m).map_err(|e| format!("{e:?}")))
        })
        .collect()
}

/// **THE REGRESSION ROW.** The obliquely-placed part whose cylindrical
/// face carries a two-`EDGE_CURVE` vertical boundary meshes watertight,
/// and meshes *exactly* the same size as the axis-aligned statement of
/// the same part — which is the invariant, not the count: a rigid
/// placement is not supposed to change how many triangles a body takes.
///
/// Goes red on `main`: `split_oblique` returns `Ok` with a
/// `NonManifoldEdge` mesh and one extra triangle, the sliver the
/// wobbling column makes the CDT emit.
#[test]
fn a_split_iso_side_meshes_watertight_under_an_oblique_placement() {
    // Imported and tessellated ONCE per fixture; every assertion below
    // reads this table. `meshed` is two full `tessellate` runs, so a
    // second call per fixture buys nothing but wall time.
    let rows: Vec<(&str, Rows)> = [
        "plain_axis.step",
        "split_axis.step",
        "plain_oblique.step",
        "split_oblique.step",
    ]
    .into_iter()
    .map(|name| (name, meshed(name)))
    .collect();
    let counts = |name: &str| -> Vec<usize> {
        rows.iter()
            .find(|(n, _)| *n == name)
            .map(|(_, r)| r.iter().map(|&(n, _)| n).collect())
            .unwrap()
    };

    for (name, rs) in &rows {
        for (i, (n, verdict)) in rs.iter().enumerate() {
            assert!(*n > 0, "{name} row {i} meshed nothing");
            assert_eq!(*verdict, Ok(()), "{name} row {i} ({n} triangles)");
        }
    }
    // The placement-invariance half, stated as a comparison rather
    // than as pinned constants so a δ or chord-policy change moves both
    // sides together.
    let oblique = counts("split_oblique.step");
    assert_eq!(
        counts("split_axis.step"),
        oblique,
        "the same part, stated axis-aligned and obliquely, must mesh to the same size"
    );
    // And the split statement costs exactly the two extra boundary
    // vertices' worth of triangles over the unsplit one, not a sliver
    // on top of them.
    for (p, o) in counts("plain_oblique.step").iter().zip(&oblique) {
        assert_eq!(o - p, 2, "the split boundary costs 2 triangles, not 3");
    }
}
