//! **The sole-`T: Bounds` roster, computed.**
//!
//! [`geom_core::Bounds`]'s scope rule prescribes the SOLE bound — a
//! parameter whose only bound is the bracket door — and that is exactly
//! the form no instrument watches: `scripts/gates/bounds-allowlist.sh`
//! plants a sole bracket bound as its must-not-fire case, because firing
//! on it would red every certification file in `geom` and `geom-brep`.
//! The rule the gate enforces is the COMPOUND one. This suite is the
//! other half: it walks every crate's `src/` and pins the sole-bound
//! roster with a disposition per door, so a new one cannot arrive
//! unnoticed the way the six in `topo` did.
//!
//! **Why a roster and not a threshold.** The population is large and
//! mostly legitimate, so a count would move for reasons nobody wants to
//! read about and an allowlist of files would say nothing about which
//! doors are in them. What a reader needs is the door and the reason it
//! is sound at a `Dual` — which is the disposition column, and which is
//! also the column a grep cannot compute. The set equality below is what
//! keeps the column honest: a door that arrives, moves crate, or is
//! deleted reds this suite until someone writes its line.
//!
//! # What the walk matches, and what it cannot
//!
//! It reads every `crates/*/src/**/*.rs` through
//! [`test_utils::source::code_only`], so a bound named in prose or inside
//! a string literal is not a hit, and a real site commented out stops
//! being one — the direction that matters. Inside that view it takes
//! every generic parameter list introduced by `fn` / `impl` / `struct` /
//! `trait` / `enum` / `type`, splits it at top-level commas (so a
//! multi-line list, and a list whose other parameters are lifetimes or
//! consts, are read the same as a one-line one), and keeps the parameters
//! whose WHOLE bound is `Bounds` or `Enclosure`, path-qualified or not.
//! `where` clauses are read the same way.
//!
//! **What it cannot match, stated rather than left to be discovered:**
//!
//! 1. **`impl Bounds` in argument position** — `fn f(x: impl Bounds)` is
//!    the same door with no generic parameter to read. None exists today.
//! 2. **A renamed import** (`use geom_core::Bounds as Bracket;`), which
//!    makes the bound spell a name this walk does not know. None exists
//!    today; the gate's KNOWN GAP 3/4 is the same hole one form over.
//! 3. **A bound reached by a supertrait obligation** — the gate's KNOWN
//!    GAP 2, and `S213`'s subject: `trait Lane: Bounds` puts the bracket
//!    door on every `T: Lane` without spelling it here.
//! 4. **A bound generated by a macro** whose text is assembled rather
//!    than written (`concat_idents!`, a bound pasted from a macro
//!    argument). A macro BODY written out in the file is matched — the
//!    `geom` projection impls below are inside one.
//!
//! Closing (2) and (3) for the tree needs a walk of every generic
//! parameter's RESOLVED bound set — a `rustc` driver or a
//! `rust-analyzer` query, not a bigger regex — which is the standing
//! answer this file does not replace.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

/// Why a sole bracket bound is sound at this door — the column a grep
/// cannot compute, and the reason this file is a roster rather than a
/// count.
#[derive(Debug, Clone, Copy)]
enum Why {
    /// The bracket read becomes an `f64` payload and stops: a box
    /// endpoint, an error field, a report. Sound at a dual by
    /// delegation (`real.rs`'s DL5(a)) — a dual's bracket is its value
    /// channel's, so the payload is the base scalar's.
    Payload(&'static str),
    /// The read SELECTS among constructions whose classification is
    /// value-channel-decided and whose selected quantity is locally
    /// constant — DL5(b). The condition is load-bearing: this is the
    /// class `geom::projection_policy`'s `mid` freeze (#874) sits
    /// outside.
    Selection(&'static str),
    /// A blanket or per-scalar `impl` whose bound is the door itself
    /// rather than a consumer of it.
    Impl(&'static str),
    /// Another track's ground, with the row that owns it.
    HandedOff(&'static str),
}

/// One sole-bound site: where it is, what it is, and why it is sound.
///
/// Keyed on the SYMBOL, never on a line number — S88's own lesson, and
/// the reason its `profile` citations had gone stale by two merges.
struct Site {
    path: &'static str,
    subject: &'static str,
    why: Why,
}

use Why::{HandedOff, Impl, Payload, Selection};

/// The roster. Every sole-`T: Bounds` / `T: Enclosure` door in
/// `crates/*/src`, and the reason each one is sound at a scalar that may
/// not certify.
const ROSTER: &[Site] = &[
    Site {
        path: "crates/bvh/src/aabb.rs",
        subject: "from_points",
        why: Payload(
            "the vertex-extent box constructor: every `geom` box funnels into it and the \
             endpoints go into an f64 `Aabb` and stop",
        ),
    },
    Site {
        path: "crates/geom-brep/src/ssi.rs",
        subject: "impl<T: geom_core::Bounds> TubeScale<T>",
        why: HandedOff("Track Q's ssi ground; enumerated by S88 and not taken there"),
    },
    Site {
        path: "crates/geom-brep/src/ssi/certify.rs",
        subject: "composite_form",
        why: HandedOff("Track Q's; a private helper S88's census names"),
    },
    Site {
        path: "crates/geom-brep/src/ssi/certify.rs",
        subject: "exact",
        why: HandedOff("Track Q's; a private helper S88's census names"),
    },
    Site {
        path: "crates/geom-brep/src/ssi/certify.rs",
        subject: "exact3",
        why: HandedOff("Track Q's; a private helper S88's census names"),
    },
    Site {
        path: "crates/geom-core/src/dual.rs",
        subject: "impl<T> Bounds for Dual<T>",
        why: Impl(
            "the D1 impl itself, written with a where-clause so the obligation reads \
             directly; the gate's KNOWN GAP 2 sanctions this exact spelling",
        ),
    },
    Site {
        path: "crates/geom-core/src/real.rs",
        subject: "impl<T: Bounds> Enclosure for T",
        why: Impl(
            "the one-line seam that makes every `Bounds` scalar an `Enclosure` — and \
             therefore makes a `Dual` one, which is issue #701",
        ),
    },
    Site {
        path: "crates/geom/src/curves/boxes.rs",
        subject: "circle_arc_aabb",
        why: Payload("an f64 box of an arc; D9 makes a dual's box the value channel's"),
    },
    Site {
        path: "crates/geom/src/curves/boxes.rs",
        subject: "ellipse_arc_aabb",
        why: Payload("as the arc constructor above"),
    },
    Site {
        path: "crates/geom/src/curves/boxes.rs",
        subject: "nurbs_curve_aabb",
        why: Payload("bracket reads only, no arithmetic on the bracket"),
    },
    Site {
        path: "crates/geom/src/curves/boxes.rs",
        subject: "of",
        why: Payload("`Brk::of`, the mechanism the two arc constructors share"),
    },
    Site {
        path: "crates/geom/src/curves/projection.rs",
        subject: "impl<T: Bounds> $Curve<T>",
        why: Selection(
            "inside the projection macro body: the seed and box doors that keep the sole \
             bound, the ones that freeze a derivative having tightened to CertifiedBounds",
        ),
    },
    Site {
        path: "crates/geom/src/projection_policy.rs",
        subject: "mid",
        why: Selection(
            "the freeze site itself, and the home of the locally-constant condition DL5(b) \
             turns on (#874)",
        ),
    },
    Site {
        path: "crates/geom/src/surfaces/boxes.rs",
        subject: "nurbs_surface_aabb",
        why: Payload("as the curve box constructors"),
    },
    Site {
        path: "crates/geom/src/surfaces/projection.rs",
        subject: "impl<T: Bounds> NurbsSurface<T>",
        why: Selection("the surface half of the projection impl above"),
    },
    Site {
        path: "crates/profile/src/fillet_select.rs",
        subject: "nearest_joint",
        why: HandedOff("Track V's ground; S88 hands it off and re-derives the citation"),
    },
    Site {
        path: "crates/profile/src/path/arc_fillet.rs",
        subject: "map_refusal",
        why: HandedOff("Track V's; a refusal-payload door S88's handoff names"),
    },
    Site {
        path: "crates/topo/src/boolean/boxes.rs",
        subject: "bracket_point",
        why: Payload("the C10 span-box reader: brackets into an f64 `SpanBox`"),
    },
    Site {
        path: "crates/topo/src/boolean/boxes.rs",
        subject: "bracket_span",
        why: Payload("as `bracket_point`, one axis at a time"),
    },
    Site {
        path: "crates/topo/src/boolean/boxes.rs",
        subject: "bracket_vector",
        why: Payload("as `bracket_point`, over a vector"),
    },
    Site {
        path: "crates/topo/src/chart_region.rs",
        subject: "definite_diag",
        why: Payload("echoes a classified margin's conservative end into a diagnostic"),
    },
    Site {
        path: "crates/topo/src/chart_region.rs",
        subject: "exact_pair",
        why: Selection(
            "the bit-identical-region fast path: an exact-f64 structure read, which is \
             locally constant by construction",
        ),
    },
    Site {
        path: "crates/topo/src/chart_region.rs",
        subject: "exact_zero",
        why: Selection("the C6 inventory gate's `is the trig channel exactly 0.0` read"),
    },
];

/// The repository root: this crate's directory, two levels up. The
/// both-ways resolution is [`test_utils::source::crate_dir`]'s, shared.
fn repo_root() -> PathBuf {
    let root = test_utils::source::crate_dir(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("the repository root resolves");
    assert!(
        root.join("Cargo.toml").is_file(),
        "{} is not the repository root",
        root.display()
    );
    root
}

/// Is this bound spelled as the bracket door alone?
fn is_sole_bracket(bound: &str) -> bool {
    let b: String = bound.split_whitespace().collect();
    matches!(
        b.trim_end_matches(','),
        "Bounds" | "Enclosure" | "geom_core::Bounds" | "geom_core::Enclosure" | "crate::Bounds"
    )
}

/// The end of the `<…>` opened at `open`, by angle depth.
///
/// **A list this cannot close stops the census** rather than being
/// skipped: angle brackets are not reliably balanced in Rust (a `->` or a
/// comparison inside a bound breaks the count), and a site the walk
/// cannot read is a site it must not drop — `flagged_census.rs`'s
/// turbofish scan takes the same asymmetry for the same reason.
fn angle_end(code: &str, open: usize) -> usize {
    let mut depth = 0i32;
    for (i, ch) in code[open..].char_indices() {
        match ch {
            '<' => depth += 1,
            '>' => {
                depth -= 1;
                if depth == 0 {
                    return open + i;
                }
            }
            '{' | ';' => break,
            _ => {}
        }
    }
    panic!(
        "a generic parameter list at byte {open} does not close before its item's body: {:.120}",
        &code[open..]
    )
}

/// Split at top-level commas, ignoring commas nested in any bracket.
fn top_level_params(inner: &str) -> Vec<&str> {
    let (mut out, mut depth, mut start) = (Vec::new(), 0i32, 0usize);
    for (i, ch) in inner.char_indices() {
        match ch {
            '<' | '(' | '[' => depth += 1,
            '>' | ')' | ']' => depth -= 1,
            ',' if depth == 0 => {
                out.push(&inner[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }
    out.push(&inner[start..]);
    out
}

/// The `where` clause between an item's generic list and its body, if it
/// has one. Found by the KEYWORD rather than by `"where "`: `rustfmt` puts
/// a multi-line clause's first bound on the next line, which is how the
/// one where-clause site in the tree (`impl Bounds for Dual<T>`) is
/// written and how a search for the keyword-plus-space misses it.
fn where_clause(after_list: &str) -> Option<&str> {
    let head = after_list.split('{').next()?;
    let at = head.find("where")?;
    let before_ok = at == 0 || !is_ident(head.as_bytes()[at - 1]);
    let rest = &head[at + 5..];
    if !before_ok || !rest.starts_with(char::is_whitespace) {
        return None;
    }
    Some(rest)
}

/// The subject a site is keyed on: the function's name, or the impl
/// header with its generic list, whitespace-collapsed.
fn subject_of(code: &str, keyword: &str, kw_at: usize, list_end: usize) -> String {
    if keyword == "impl" {
        let head = &code[kw_at..list_end + 1];
        let head: String = head.split_whitespace().collect::<Vec<_>>().join(" ");
        // `impl<T: Bounds> Enclosure for T {` keys on the whole header;
        // the trailing type is what tells the two projection impls apart.
        let tail = code[list_end + 1..]
            .split('{')
            .next()
            .unwrap_or("")
            .split("where")
            .next()
            .unwrap_or("")
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        return format!("{head} {tail}").trim().to_string();
    }
    code[kw_at + keyword.len()..]
        .trim_start()
        .split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .next()
        .unwrap_or("")
        .to_string()
}

/// Every sole-bracket-bound site under `crates/*/src`, as
/// `(path, subject)`.
fn walk(root: &Path) -> BTreeSet<(String, String)> {
    let mut out = BTreeSet::new();
    let crates = root.join("crates");
    for entry in std::fs::read_dir(&crates).expect("crates dir listing") {
        let src = entry.expect("dir entry").path().join("src");
        if !src.is_dir() {
            continue;
        }
        for path in test_utils::source::rust_sources(&src) {
            let text = std::fs::read_to_string(&path).expect("readable source file");
            let code = test_utils::source::code_only(&text);
            let rel = path
                .strip_prefix(root)
                .expect("a walked file lies under the root")
                .to_string_lossy()
                .replace('\\', "/");
            for (kw_at, keyword) in item_keywords(&code) {
                let after = &code[kw_at + keyword.len()..];
                let Some(rel_open) = after.find(['<', '{', ';', '(']) else {
                    continue;
                };
                if !after[rel_open..].starts_with('<') {
                    continue;
                }
                let open = kw_at + keyword.len() + rel_open;
                let end = angle_end(&code, open);
                let mut hit = top_level_params(&code[open + 1..end])
                    .iter()
                    .filter_map(|p| p.split_once(':'))
                    .any(|(_, bound)| is_sole_bracket(bound));
                // The `where` clause of the same item, read the same way.
                if !hit && let Some(clause) = where_clause(&code[end..]) {
                    hit = top_level_params(clause)
                        .iter()
                        .filter_map(|p| p.split_once(':'))
                        .any(|(_, bound)| is_sole_bracket(bound));
                }
                if hit {
                    out.insert((rel.clone(), subject_of(&code, keyword, kw_at, end)));
                }
            }
        }
    }
    out
}

/// Every `fn` / `impl` / `struct` / `trait` / `enum` / `type` keyword in
/// the code view, as `(offset, keyword)`, with word boundaries checked so
/// `transform` does not contain a `fn`.
fn item_keywords(code: &str) -> Vec<(usize, &'static str)> {
    let mut out = Vec::new();
    for kw in ["fn", "impl", "struct", "trait", "enum", "type"] {
        let mut i = 0;
        while let Some(rel) = code[i..].find(kw) {
            let at = i + rel;
            i = at + kw.len();
            let before_ok = at == 0 || !is_ident(code.as_bytes()[at - 1]);
            let after_ok = code.as_bytes().get(i).is_none_or(|b| !is_ident(*b));
            if before_ok && after_ok {
                out.push((at, kw));
            }
        }
    }
    out.sort_unstable();
    out
}

fn is_ident(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

/// **The roster is the tree's set, not a subset of it.**
///
/// A door that arrives, moves, or is deleted reds this row until its line
/// is written or removed — which is the whole instrument: the rule that
/// prescribes the sole bound now has something that watches the class,
/// and it is not the gate (which cannot see this form by construction).
#[test]
fn every_sole_bracket_bound_door_is_in_the_roster() {
    let root = repo_root();
    let found = walk(&root);
    let listed: BTreeSet<(String, String)> = ROSTER
        .iter()
        .map(|s| (s.path.to_string(), s.subject.to_string()))
        .collect();
    let arrived: Vec<_> = found.difference(&listed).collect();
    let gone: Vec<_> = listed.difference(&found).collect();
    assert!(
        arrived.is_empty() && gone.is_empty(),
        "the sole-bracket-bound roster no longer matches the tree.\n  \
         arrived or moved (owe a roster line WITH its disposition): {arrived:#?}\n  \
         listed but no longer present (delete the line): {gone:#?}"
    );
}

/// A disposition is a claim, and an empty one is a line that looks
/// discharged and is not. (`reader_census.rs` carries this row for its
/// own ledger; the shape is deliberately the same.)
#[test]
fn every_roster_line_states_a_reason() {
    for site in ROSTER {
        let reason = match site.why {
            Payload(r) | Selection(r) | Impl(r) | HandedOff(r) => r,
        };
        assert!(
            reason.len() > 20,
            "{}::{} carries no real reason: {reason:?}",
            site.path,
            site.subject
        );
    }
}
