//! **The certified door's postcondition, pinned as one generic body and
//! swept per implementor.**
//!
//! [`CertifiedEnclosure::certified_bracket`] promises that `Some((lo,
//! hi))` brackets every real the value stands for. A pair of NaNs
//! brackets nothing, so a door that hands one back has certified poison
//! — and NaN is the one shape that laundering hides in, because it is
//! indistinguishable from arithmetic poison and travels silently through
//! the `f64` combinators (`f64::max` returns the non-NaN operand).
//!
//! Two properties, and the second is the reason this suite is a sweep
//! rather than a fixture:
//!
//! 1. **No `Some` carries a NaN end**, for any implementor. Written once,
//!    generically, so it is the *trait's* postcondition that is under
//!    test and not one type's spelling of it.
//! 2. **Each door refuses exactly on its own poison** — never less (that
//!    is the laundering) and never more (a door that refused everything
//!    would satisfy property 1 and certify nothing). What catches the
//!    refuse-all direction is the per-member **agreement** assertion
//!    (`assert_eq!(ok, !x.is_nan())` and its siblings), not the vacuity
//!    counters: the counters only prove the corpus reached both sides, and
//!    a corpus that drifted entirely to one side fails on them rather than
//!    passing quietly. Both mechanisms are stated because they catch
//!    different things and only one of them catches the direction this
//!    change actually risks.
//!
//! The corpora are **generated by arithmetic** over a handful of seeds,
//! not enumerated as answers. An operation added to a scalar, or an
//! existing one changed to fabricate a bracket where it used to poison,
//! is swept the next time this runs without anyone editing a fixture
//! list. That is the difference between a row that goes red when the
//! guarantee degrades and a row that goes red only at the value someone
//! thought of.
//!
//! **Every row here executes on CI, the `probe` one included** — the
//! non-probe rows on every run, the `probe` row on 1 run in 5. The
//! suite is rostered in `scripts/gates/probe-suite-census.sh`'s
//! `RUN_FLOOR`, so `scripts/k_probe_sweep.sh`'s roster-driven
//! `run_plain` selects it under `--features probe`, and the census's
//! `--check-executed` complement fails if that invocation is ever
//! dropped. `k_probe_sweep.sh` rides the `k-lint` job's `dev-probe`
//! row, and every code-tier run gates all five of that job's feature
//! unifications as five matrix legs — so this row runs on every
//! building merge.
//!
//! **It was 1 in 5 from 2026-08-22 to 2026-09-04**, when the row was
//! drawn from the head SHA. That sampling was sound here and NOT in
//! general: this row is a PERSISTENCE detector — a degraded certified
//! door stays degraded in the tree, so a later draw still found it, and
//! the red was deferred rather than lost. The ABSENCE half is
//! deliberately not sampled: `--check-executed` and the `RUN_FLOOR` it
//! reads run unconditionally
//! in the `discipline` job, because a suite that DISAPPEARS leaves no
//! future red to catch and would merge silently, once. A probe-gated
//! body nobody runs is the state that roster exists to end, and this
//! one had no reason to be in it.
//!
//! Refusal is not free-standing: what a refusal *does* is cross into
//! certification arithmetic as a refusal. The last rows pin that, per corpus member, at
//! [`Interval::from_certified`] — the one body every lane scalar
//! reaches certification arithmetic through.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use geom_core::Bounds;
use geom_core::interval::certification::Certification;
use geom_core::{CertifiedEnclosure, Interval};
use interval_transcendentals::{DInterval, Decoration};

/// The trait's postcondition, in one body: a `Some` is a real bracket.
/// Returns whether the door certified, so callers can count.
#[track_caller]
fn door_certifies<T: CertifiedEnclosure>(tag: &str, x: T) -> bool {
    match x.certified_bracket() {
        None => false,
        Some((lo, hi)) => {
            assert!(
                !lo.is_nan() && !hi.is_nan(),
                "{tag}: the certified door handed back Some(({lo}, {hi})) — \
                 a NaN end is poison, and certifying it is the laundering \
                 the trait doc excludes. `None` is the refusal."
            );
            assert!(
                lo <= hi,
                "{tag}: the certified door handed back the inverted bracket \
                 ({lo}, {hi}), which encloses nothing."
            );
            true
        }
    }
}

/// Both halves must be reached, or the sweep proves nothing.
#[track_caller]
fn assert_non_vacuous(what: &str, certified: usize, refused: usize) {
    assert!(
        certified > 0,
        "{what}: nothing certified — the sweep is vacuous"
    );
    assert!(
        refused > 0,
        "{what}: nothing refused — the sweep is vacuous"
    );
}

// ---------------------------------------------------------------- f64

/// Seeds, plus every value the four operations and `sqrt` reach from
/// them — `0/0`, `∞−∞` and `sqrt(−1)` are how NaN actually arrives at
/// this lane, and none of them is written down as a NaN.
fn f64_corpus() -> Vec<(String, f64)> {
    let seeds = [
        0.0,
        -0.0,
        1.0,
        -1.0,
        1e308,
        f64::INFINITY,
        f64::NEG_INFINITY,
    ];
    let mut out: Vec<(String, f64)> = seeds.iter().map(|&a| (format!("{a}"), a)).collect();
    for &a in &seeds {
        out.push((format!("sqrt({a})"), a.sqrt()));
        for &b in &seeds {
            out.push((format!("{a}+{b}"), a + b));
            out.push((format!("{a}-{b}"), a - b));
            out.push((format!("{a}*{b}"), a * b));
            out.push((format!("{a}/{b}"), a / b));
        }
    }
    out
}

/// `f64`'s poison is NaN and nothing else: ∞ is not poison (D4's Q1
/// residue), so it certifies the degenerate bracket it is and interval arithmetic
/// crossing — not this door — is where it stops.
#[test]
fn the_f64_door_refuses_exactly_its_nans() {
    let (mut certified, mut refused) = (0, 0);
    for (tag, x) in f64_corpus() {
        let ok = door_certifies(&tag, x);
        assert_eq!(
            ok,
            !x.is_nan(),
            "{tag} = {x}: the f64 door and f64 poison disagree"
        );
        if ok {
            assert_eq!(x.certified_bracket(), Some((x, x)), "{tag}: bracket moved");
            certified += 1;
        } else {
            refused += 1;
        }
    }
    assert_non_vacuous("f64", certified, refused);
}

// -------------------------------------------------------- Interval

/// Seeds spanning both states (certified and refused) and both infinite
/// sides, plus every value the certification doors and operators reach
/// from them. `x / [0, 0]` and `[0, 0] * [−∞, ∞]` are how refusals
/// arrive without being written down.
fn ring_corpus() -> Vec<(String, Interval)> {
    let seeds = [
        ("[0,0]", Interval::point(0.0)),
        ("[1,2]", Interval::from_bounds(1.0, 2.0)),
        ("[-1,1]", Interval::from_bounds(-1.0, 1.0)),
        ("[-inf,0]", Interval::from_bounds(f64::NEG_INFINITY, 0.0)),
        ("[0,inf]", Interval::from_bounds(0.0, f64::INFINITY)),
        ("poison", Interval::refused()),
        ("inverted", Interval::from_bounds(1.0, -1.0)),
    ];
    let mut out: Vec<(String, Interval)> = seeds.iter().map(|&(t, r)| (t.to_string(), r)).collect();
    for &(ta, a) in &seeds {
        out.push((format!("-{ta}"), -a));
        out.push((format!("{ta}.sqr()"), a.sqr()));
        out.push((format!("{ta}.powi(0)"), a.powi(0)));
        out.push((format!("{ta}.powi(3)"), a.powi(3)));
        out.push((format!("{ta}.clamped_to(-1,1)"), a.clamped_to(-1.0, 1.0)));
        for &(tb, b) in &seeds {
            out.push((format!("{ta}+{tb}"), a + b));
            out.push((format!("{ta}-{tb}"), a - b));
            out.push((format!("{ta}*{tb}"), a * b));
            out.push((format!("{ta}/{tb}"), a / b));
            out.push((format!("hull({ta},{tb})"), Interval::hull(a, b)));
        }
    }
    out
}

/// **The row S86 is about.** A refusal is the decoration it
/// carries (`dec < Def`, NaI and empty below that), so `is_certified` is
/// its whole domain-violation channel and the door has to consult it — a
/// refused enclosure's endpoints are ordinary numbers and certify
/// nothing. A door that certified on the endpoints alone reds here on
/// the first refused member.
#[test]
fn the_ring_door_refuses_exactly_its_poison() {
    let (mut certified, mut refused) = (0, 0);
    for (tag, r) in ring_corpus() {
        let ok = door_certifies(&tag, r);
        assert_eq!(
            ok,
            r.is_certified(),
            "{tag} = {r:?}: the certified door and `is_certified` disagree"
        );
        if ok {
            assert_eq!(
                r.certified_bracket(),
                Some((r.lo(), r.hi())),
                "{tag}: a certified enclosure must hand over its own endpoints"
            );
            certified += 1;
        } else {
            refused += 1;
        }
    }
    assert_non_vacuous("Interval", certified, refused);
}

/// Poison has to be **reachable by arithmetic**, or the refusing half of
/// the sweep above is a hand-built seed testing itself.
///
/// Every producer inside certification arithmetic is a division: an explicit one by a
/// divisor not proven away from zero, or a negative integer power,
/// which is the reciprocal of the positive one. The three rows below
/// are the three shapes a division answers with — the empty set, an
/// unbounded half-line, and a bounded bracket — so the row is not one
/// witness wearing three names.
#[test]
fn ring_poison_is_reached_by_arithmetic_not_only_by_construction() {
    let derived = [
        (
            "[1,2]/[0,0]",
            Interval::from_bounds(1.0, 2.0) / Interval::point(0.0),
        ),
        (
            "[-2,-1]/[0,5e-324]",
            Interval::from_bounds(-2.0, -1.0) / Interval::from_bounds(0.0, 5e-324),
        ),
        (
            "[5e-324,1].powi(-1)",
            Interval::from_bounds(5e-324, 1.0).powi(-1),
        ),
    ];
    for (tag, r) in derived {
        assert!(!r.is_certified(), "{tag} was expected to poison, got {r:?}");
        assert!(
            r.certified_bracket().is_none(),
            "{tag}: arithmetic poison certified"
        );
    }
}

/// **The shape that launders: a refusal whose endpoints are REAL.**
///
/// The two rows above are a refusal, which is a NaN pair, and
/// the backend answers the first of them with the empty set — also NaN
/// ends. Neither witnesses the case this file exists for, because a
/// NaN end is caught by property 1 whatever carries it.
///
/// The case that needs writing down is a backend refusal that carries
/// ordinary finite or infinite endpoints: `dec < Def` with nothing in
/// `lo`/`hi` to give it away. There every unguarded `.lo()`/`.hi()`
/// read downstream takes the certifying branch, and only the door's
/// own refusal stops it. Both derivations below are pure ring
/// arithmetic, so a consumer reaches them without constructing
/// anything by hand.
#[test]
fn a_backend_refusal_can_carry_real_endpoints() {
    let half_line = DInterval::from_bounds(-2.0, -1.0) / DInterval::from_bounds(0.0, 5e-324);
    let finite = (DInterval::from_bounds(-2.0, -1.0) / DInterval::from_bounds(-1.0, 1.0))
        * DInterval::from_bounds(0.0, 0.0);
    for (tag, d, ends) in [
        (
            "[-2,-1] / [0,5e-324]",
            half_line,
            (f64::NEG_INFINITY, -f64::MAX),
        ),
        ("([-2,-1] / [-1,1]) * [0,0]", finite, (0.0, 0.0)),
    ] {
        assert!(!d.is_nai() && !d.is_empty(), "{tag}: {d:?}");
        assert!(
            d.decoration() < Decoration::Def,
            "{tag} is a refusal in the decoration channel: {d:?}"
        );
        assert_eq!((d.lo(), d.hi()), ends, "{tag}: {d:?}");
        assert!(
            !d.lo().is_nan() && !d.hi().is_nan(),
            "{tag}: the endpoints are real, which is the whole point"
        );
    }
    // Both refuse, and the brackets above are what a refusal carries:
    // `is_certified` is the only thing that says no.
    assert!(
        !(Interval::from_bounds(-2.0, -1.0) / Interval::from_bounds(0.0, 5e-324)).is_certified()
    );
    assert!(
        !((Interval::from_bounds(-2.0, -1.0) / Interval::from_bounds(-1.0, 1.0))
            * Interval::from_bounds(0.0, 0.0))
        .is_certified()
    );
}

// ------------------------------------- what a refusal does downstream

/// **A refusal crosses as poison, at the door's expense rather than the
/// constructor's.** `from_certified` is the one body every lane scalar
/// reaches certification arithmetic through, and the claim it used to rest on —
/// *`from_bounds` rejects the NaN pair downstream* — is now redundant
/// rather than load-bearing. Pinned per corpus member so it stays a
/// verified agreement and not an assumption.
#[test]
fn every_refused_ring_crosses_as_poison() {
    let (mut certified, mut refused) = (0, 0);
    for (tag, r) in ring_corpus() {
        let crossed = Interval::from_certified(r);
        if r.certified_bracket().is_none() {
            assert!(
                !crossed.is_certified(),
                "{tag}: a refused operand crossed as {crossed:?}"
            );
            refused += 1;
        } else {
            assert!(
                crossed.is_certified(),
                "{tag}: a CERTIFIED operand crossed as poison. Interval arithmetic \
                 cannot hold a closed side at infinity, so nothing it \
                 certifies may be rejected by `from_bounds`."
            );
            certified += 1;
        }
    }
    // Two-sided deliberately: with only the refused counter, a door that
    // refused EVERYTHING would leave this row green while every other row
    // went red, and this is the row about what refusal does.
    assert_non_vacuous("interval arithmetic crossing", certified, refused);
}

/// The f64 half of the same crossing, stated as the exact boundary:
/// **a finite `f64` crosses carrying its own value, and nothing else
/// crosses at all.** NaN is stopped at the door now; ±∞ certifies and is
/// stopped one step later by `from_bounds`, which rules that a closed
/// side at infinity encloses no real. Both arrive as poison, and the row
/// records which stopped what rather than leaving the pair
/// interchangeable.
#[test]
fn the_f64_crossing_admits_exactly_the_finite() {
    let (mut crossed, mut poisoned) = (0, 0);
    for (tag, x) in f64_corpus() {
        let r = Interval::from_certified(x);
        assert_eq!(
            r.is_certified(),
            x.is_finite(),
            "{tag} = {x} crossed as {r:?}"
        );
        if x.is_finite() {
            assert_eq!((r.lo(), r.hi()), (x, x), "{tag}: the crossing moved it");
            crossed += 1;
        } else {
            assert_eq!(
                x.is_nan(),
                x.certified_bracket().is_none(),
                "{tag}: the door stopped the wrong non-finite"
            );
            poisoned += 1;
        }
    }
    assert_non_vacuous("the f64 crossing", crossed, poisoned);
}

// -------------------------------------------- the interval implementors

mod interval_lane {
    use geom_core::{Interval, Real};

    use super::{assert_non_vacuous, door_certifies};

    /// `sqrt([a, 4])` degrades exactly when `a < 0` forces a clamp, so
    /// the sweep walks the operand across the domain boundary instead of
    /// probing one side of it. Empty (`sqrt([−4, −1])`) and NaI store NaN
    /// brackets, so they are the members that would show a laundering
    /// door as NaN rather than as a merely-uncertified answer.
    #[test]
    fn the_interval_door_refuses_exactly_below_def() {
        let (mut certified, mut refused) = (0, 0);
        let mut corpus: Vec<(String, Interval)> = Vec::new();
        for a in [-4.0, -1.0, -0.25, -1e-300, 0.0, 1e-300, 0.25, 1.0, 4.0] {
            corpus.push((
                format!("sqrt([{a}, 4])"),
                Interval::from_bounds(a, 4.0).sqrt(),
            ));
            corpus.push((
                format!("sqrt([-4, {a}])"),
                Interval::from_bounds(-4.0, a).sqrt(),
            ));
        }
        corpus.push(("NaI".to_string(), Interval::from_f64(f64::NAN)));
        corpus.push((
            "entire".to_string(),
            Interval::from_bounds(f64::NEG_INFINITY, f64::INFINITY),
        ));
        for (tag, x) in corpus {
            let ok = door_certifies(&tag, x);
            assert_eq!(
                ok,
                x.is_certified(),
                "{tag}: the interval door and the `Def` threshold disagree"
            );
            if ok { certified += 1 } else { refused += 1 }
        }
        assert_non_vacuous("Interval", certified, refused);
    }
}

#[cfg(feature = "probe")]
mod probe_lane {
    use geom_core::{CertifiedEnclosure, Probe};

    use super::{assert_non_vacuous, door_certifies, f64_corpus};

    /// D9 forbids the recording lane diverging from `f64`, so the row is
    /// the *agreement* rather than a second copy of the f64 expectation:
    /// every member of the f64 corpus must get the same answer through
    /// both doors.
    #[test]
    fn the_probe_door_answers_exactly_as_f64() {
        let (mut certified, mut refused) = (0, 0);
        for (tag, x) in f64_corpus() {
            let p = Probe(x);
            let ok = door_certifies(&tag, p);
            assert_eq!(
                p.certified_bracket(),
                x.certified_bracket(),
                "{tag}: the probe lane diverged from f64"
            );
            if ok { certified += 1 } else { refused += 1 }
        }
        assert_non_vacuous("Probe", certified, refused);
    }
}
