//! **The certified door's postcondition, pinned as one generic body and
//! swept per implementor.**
//!
//! [`CertifiedEnclosure::certified_bracket`] promises that `Some((lo,
//! hi))` brackets every real the value stands for. A pair of NaNs
//! brackets nothing, so a door that hands one back has certified poison
//! — and NaN is the one shape that laundering hides in, because it is
//! indistinguishable from arithmetic poison and travels silently through
//! the `f64` combinators (`f64::max` returns the non-NaN operand).
//!
//! Two properties, and the second is the reason this suite is a sweep
//! rather than a fixture:
//!
//! 1. **No `Some` carries a NaN end**, for any implementor. Written once,
//!    generically, so it is the *trait's* postcondition that is under
//!    test and not one type's spelling of it.
//! 2. **Each door refuses exactly on its own poison** — never less (that
//!    is the laundering) and never more (a door that refused everything
//!    would satisfy property 1 and certify nothing). What catches the
//!    refuse-all direction is the per-member **agreement** assertion
//!    (`assert_eq!(ok, !x.is_nan())` and its siblings), not the vacuity
//!    counters: the counters only prove the corpus reached both sides, and
//!    a corpus that drifted entirely to one side fails on them rather than
//!    passing quietly. Both mechanisms are stated because they catch
//!    different things and only one of them catches the direction this
//!    change actually risks.
//!
//! The corpora are **generated by arithmetic** over a handful of seeds,
//! not enumerated as answers. An operation added to a scalar, or an
//! existing one changed to fabricate a bracket where it used to poison,
//! is swept the next time this runs without anyone editing a fixture
//! list. That is the difference between a row that goes red when the
//! guarantee degrades and a row that goes red only at the value someone
//! thought of.
//!
//! **Every row here executes on CI, the `probe` one included.** The suite
//! is rostered in `scripts/gates/probe-suite-census.sh`'s `RUN_FLOOR`, so
//! `scripts/k_probe_sweep.sh`'s roster-driven `run_plain` selects it under
//! `--features probe` on every merge and the census's `--check-executed`
//! complement fails if that invocation is ever dropped. A probe-gated body
//! nobody runs is the state that roster exists to end, and this one had no
//! reason to be in it.
//!
//! Refusal is not free-standing: what a refusal *does* is cross into the
//! ring as poison. The last rows pin that, per corpus member, at
//! [`RingInterval::from_certified`] — the one body every lane scalar
//! reaches the C9 ring through.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use geom_core::{CertifiedEnclosure, RingInterval};

/// The trait's postcondition, in one body: a `Some` is a real bracket.
/// Returns whether the door certified, so callers can count.
#[track_caller]
fn door_certifies<T: CertifiedEnclosure>(tag: &str, x: T) -> bool {
    match x.certified_bracket() {
        None => false,
        Some((lo, hi)) => {
            assert!(
                !lo.is_nan() && !hi.is_nan(),
                "{tag}: the certified door handed back Some(({lo}, {hi})) — \
                 a NaN end is poison, and certifying it is the laundering \
                 the trait doc excludes. `None` is the refusal."
            );
            assert!(
                lo <= hi,
                "{tag}: the certified door handed back the inverted bracket \
                 ({lo}, {hi}), which encloses nothing."
            );
            true
        }
    }
}

/// Both halves must be reached, or the sweep proves nothing.
#[track_caller]
fn assert_non_vacuous(what: &str, certified: usize, refused: usize) {
    assert!(
        certified > 0,
        "{what}: nothing certified — the sweep is vacuous"
    );
    assert!(
        refused > 0,
        "{what}: nothing refused — the sweep is vacuous"
    );
}

// ---------------------------------------------------------------- f64

/// Seeds, plus every value the four operations and `sqrt` reach from
/// them — `0/0`, `∞−∞` and `sqrt(−1)` are how NaN actually arrives at
/// this lane, and none of them is written down as a NaN.
fn f64_corpus() -> Vec<(String, f64)> {
    let seeds = [
        0.0,
        -0.0,
        1.0,
        -1.0,
        1e308,
        f64::INFINITY,
        f64::NEG_INFINITY,
    ];
    let mut out: Vec<(String, f64)> = seeds.iter().map(|&a| (format!("{a}"), a)).collect();
    for &a in &seeds {
        out.push((format!("sqrt({a})"), a.sqrt()));
        for &b in &seeds {
            out.push((format!("{a}+{b}"), a + b));
            out.push((format!("{a}-{b}"), a - b));
            out.push((format!("{a}*{b}"), a * b));
            out.push((format!("{a}/{b}"), a / b));
        }
    }
    out
}

/// `f64`'s poison is NaN and nothing else: ∞ is not poison (D4's Q1
/// residue), so it certifies the degenerate bracket it is and the ring
/// crossing — not this door — is where it stops.
#[test]
fn the_f64_door_refuses_exactly_its_nans() {
    let (mut certified, mut refused) = (0, 0);
    for (tag, x) in f64_corpus() {
        let ok = door_certifies(&tag, x);
        assert_eq!(
            ok,
            !x.is_nan(),
            "{tag} = {x}: the f64 door and f64 poison disagree"
        );
        if ok {
            assert_eq!(x.certified_bracket(), Some((x, x)), "{tag}: bracket moved");
            certified += 1;
        } else {
            refused += 1;
        }
    }
    assert_non_vacuous("f64", certified, refused);
}

// -------------------------------------------------------- RingInterval

/// Seeds spanning both ring states and both infinite sides, plus every
/// value the ring's own operations reach from them. `x / [0, 0]` and
/// `[0, 0] * [−∞, ∞]` are how ring poison arrives without being written
/// down.
fn ring_corpus() -> Vec<(String, RingInterval)> {
    let seeds = [
        ("[0,0]", RingInterval::point(0.0)),
        ("[1,2]", RingInterval::from_bounds(1.0, 2.0)),
        ("[-1,1]", RingInterval::from_bounds(-1.0, 1.0)),
        (
            "[-inf,0]",
            RingInterval::from_bounds(f64::NEG_INFINITY, 0.0),
        ),
        ("[0,inf]", RingInterval::from_bounds(0.0, f64::INFINITY)),
        ("poison", RingInterval::poison()),
        ("inverted", RingInterval::from_bounds(1.0, -1.0)),
    ];
    let mut out: Vec<(String, RingInterval)> =
        seeds.iter().map(|&(t, r)| (t.to_string(), r)).collect();
    for &(ta, a) in &seeds {
        out.push((format!("-{ta}"), -a));
        out.push((format!("{ta}.sqr()"), a.sqr()));
        out.push((format!("{ta}.powi(0)"), a.powi(0)));
        out.push((format!("{ta}.powi(3)"), a.powi(3)));
        out.push((format!("{ta}.clamped_to(-1,1)"), a.clamped_to(-1.0, 1.0)));
        for &(tb, b) in &seeds {
            out.push((format!("{ta}+{tb}"), a + b));
            out.push((format!("{ta}-{tb}"), a - b));
            out.push((format!("{ta}*{tb}"), a * b));
            out.push((format!("{ta}/{tb}"), a / b));
            out.push((format!("hull({ta},{tb})"), RingInterval::hull(a, b)));
        }
    }
    out
}

/// **The row S86 is about.** The ring has two states and no decorations,
/// so `is_poison` is its whole domain-violation channel and the door has
/// to consult it. Before the fix this sweep went red on the first
/// poisoned member, which certified `Some((NaN, NaN))`.
#[test]
fn the_ring_door_refuses_exactly_its_poison() {
    let (mut certified, mut refused) = (0, 0);
    for (tag, r) in ring_corpus() {
        let ok = door_certifies(&tag, r);
        assert_eq!(
            ok,
            !r.is_poison(),
            "{tag} = {r:?}: the ring door and `is_poison` disagree"
        );
        if ok {
            assert_eq!(
                r.certified_bracket(),
                Some((r.lo(), r.hi())),
                "{tag}: a certified ring must hand over its own endpoints"
            );
            certified += 1;
        } else {
            refused += 1;
        }
    }
    assert_non_vacuous("RingInterval", certified, refused);
}

/// Poison has to be **reachable by arithmetic**, or the refusing half of
/// the sweep above is a hand-built seed testing itself.
#[test]
fn ring_poison_is_reached_by_arithmetic_not_only_by_construction() {
    let derived = [
        (
            "[1,2]/[0,0]",
            RingInterval::from_bounds(1.0, 2.0) / RingInterval::point(0.0),
        ),
        (
            "[0,1]*[0,inf]",
            RingInterval::from_bounds(0.0, 1.0) * RingInterval::from_bounds(0.0, f64::INFINITY),
        ),
    ];
    for (tag, r) in derived {
        assert!(r.is_poison(), "{tag} was expected to poison, got {r:?}");
        assert!(
            r.certified_bracket().is_none(),
            "{tag}: arithmetic poison certified"
        );
    }
}

// ------------------------------------- what a refusal does downstream

/// **A refusal crosses as poison, at the door's expense rather than the
/// constructor's.** `from_certified` is the one body every lane scalar
/// reaches the C9 ring through, and the claim it used to rest on —
/// *`from_bounds` rejects the NaN pair downstream* — is now redundant
/// rather than load-bearing. Pinned per corpus member so it stays a
/// verified agreement and not an assumption.
#[test]
fn every_refused_ring_crosses_as_poison() {
    let (mut certified, mut refused) = (0, 0);
    for (tag, r) in ring_corpus() {
        let crossed = RingInterval::from_certified(r);
        if r.certified_bracket().is_none() {
            assert!(
                crossed.is_poison(),
                "{tag}: a refused operand crossed as {crossed:?}"
            );
            refused += 1;
        } else {
            assert!(
                !crossed.is_poison(),
                "{tag}: a CERTIFIED operand crossed as poison. The ring \
                 cannot hold a closed side at infinity, so nothing it \
                 certifies may be rejected by `from_bounds`."
            );
            certified += 1;
        }
    }
    // Two-sided deliberately: with only the refused counter, a door that
    // refused EVERYTHING would leave this row green while every other row
    // went red, and this is the row about what refusal does.
    assert_non_vacuous("the ring crossing", certified, refused);
}

/// The f64 half of the same crossing, stated as the exact boundary:
/// **a finite `f64` crosses carrying its own value, and nothing else
/// crosses at all.** NaN is stopped at the door now; ±∞ certifies and is
/// stopped one step later by `from_bounds`, which rules that a closed
/// side at infinity encloses no real. Both arrive as poison, and the row
/// records which stopped what rather than leaving the pair
/// interchangeable.
#[test]
fn the_f64_crossing_admits_exactly_the_finite() {
    let (mut crossed, mut poisoned) = (0, 0);
    for (tag, x) in f64_corpus() {
        let r = RingInterval::from_certified(x);
        assert_eq!(
            !r.is_poison(),
            x.is_finite(),
            "{tag} = {x} crossed as {r:?}"
        );
        if x.is_finite() {
            assert_eq!((r.lo(), r.hi()), (x, x), "{tag}: the crossing moved it");
            crossed += 1;
        } else {
            assert_eq!(
                x.is_nan(),
                x.certified_bracket().is_none(),
                "{tag}: the door stopped the wrong non-finite"
            );
            poisoned += 1;
        }
    }
    assert_non_vacuous("the f64 crossing", crossed, poisoned);
}

// ----------------------------------------------- the gated implementors

#[cfg(feature = "interval")]
mod interval_lane {
    use geom_core::{Interval, Real};

    use super::{assert_non_vacuous, door_certifies};

    /// `sqrt([a, 4])` degrades exactly when `a < 0` forces a clamp, so
    /// the sweep walks the operand across the domain boundary instead of
    /// probing one side of it. Empty (`sqrt([−4, −1])`) and NaI store NaN
    /// brackets, so they are the members that would show a laundering
    /// door as NaN rather than as a merely-uncertified answer.
    #[test]
    fn the_interval_door_refuses_exactly_below_def() {
        let (mut certified, mut refused) = (0, 0);
        let mut corpus: Vec<(String, Interval)> = Vec::new();
        for a in [-4.0, -1.0, -0.25, -1e-300, 0.0, 1e-300, 0.25, 1.0, 4.0] {
            corpus.push((
                format!("sqrt([{a}, 4])"),
                Interval::from_bounds(a, 4.0).sqrt(),
            ));
            corpus.push((
                format!("sqrt([-4, {a}])"),
                Interval::from_bounds(-4.0, a).sqrt(),
            ));
        }
        corpus.push(("NaI".to_string(), Interval::from_f64(f64::NAN)));
        corpus.push((
            "entire".to_string(),
            Interval::from_bounds(f64::NEG_INFINITY, f64::INFINITY),
        ));
        for (tag, x) in corpus {
            let ok = door_certifies(&tag, x);
            assert_eq!(
                ok,
                x.is_certified(),
                "{tag}: the interval door and the `Def` threshold disagree"
            );
            if ok { certified += 1 } else { refused += 1 }
        }
        assert_non_vacuous("Interval", certified, refused);
    }
}

#[cfg(feature = "probe")]
mod probe_lane {
    use geom_core::{CertifiedEnclosure, Probe};

    use super::{assert_non_vacuous, door_certifies, f64_corpus};

    /// D9 forbids the recording lane diverging from `f64`, so the row is
    /// the *agreement* rather than a second copy of the f64 expectation:
    /// every member of the f64 corpus must get the same answer through
    /// both doors.
    #[test]
    fn the_probe_door_answers_exactly_as_f64() {
        let (mut certified, mut refused) = (0, 0);
        for (tag, x) in f64_corpus() {
            let p = Probe(x);
            let ok = door_certifies(&tag, p);
            assert_eq!(
                p.certified_bracket(),
                x.certified_bracket(),
                "{tag}: the probe lane diverged from f64"
            );
            if ok { certified += 1 } else { refused += 1 }
        }
        assert_non_vacuous("Probe", certified, refused);
    }
}
