//! The clause-(i) debt lane's census (the standing rule on
//! [`geom_core::k_stats::decide_flagged`]; the lane is tracked as issue
//! #214): **no new `decide_flagged` site ships without a ledger row**
//! in `docs/predicate-dimension-audit.md`. Two assertions carry it,
//! over the SHIPPED call sites only (crate `src/` trees — fixtures and
//! demos carry prose reasons instead of rows and are not counted):
//!
//! 1. the number of sites matches the ledger's inventory — F2 ×4,
//!    F10 ×1 (one loop over seven rigidity residuals), F13 ×1, F14 ×1,
//!    F15 ×1, **8 sites**;
//! 2. every site's `ledger_row` argument names a row the ledger
//!    actually has.
//!
//! (2) is what makes the fourth parameter mean something. Without it
//! the argument reaches no recorder, no column and no assertion, so a
//! site citing `"F16"` — or citing a row renumbered out from under it
//! — reads as a discharged obligation and is a string.
//!
//! Adding a site without updating BOTH the ledger and the count fails
//! the suite; retiring a flagged family (its own unit) decrements it.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

/// The ledger's current shipped `decide_flagged` inventory.
const LEDGER_FLAGGED_SITES: usize = 8;

/// One shipped call site: where it is, and the row it cites.
#[derive(Debug)]
struct Site {
    file: PathBuf,
    line: usize,
    ledger_row: String,
}

/// Finds every `decide_flagged(…)` call in `text`.
///
/// **What this pattern matches**: the identifier followed by `(`, under
/// every import spelling — `geom_core::k_stats::decide_flagged(`,
/// `k_stats::decide_flagged(`, and the bare `decide_flagged(` a `use`
/// makes available. Keying on a path prefix instead would make the
/// census a statement about how calls are SPELLED rather than about
/// how many there are — and the bare form is in use today, at three
/// sites in tests and demos.
///
/// **What it cannot match, and nothing here would notice:** a call
/// through a renamed import (`use …::decide_flagged as df;`), a call
/// generated by a macro, and a site inside a `/* … */` block comment
/// (line comments ARE stripped). A site whose `ledger_row` is not a
/// string literal — a `const`, a field, a table entry — is not skipped
/// but **fails loudly**, because a census that skipped it would report
/// a smaller tree than the one that ships. Same for a site inside a
/// `#[cfg(test)]` **function** rather than module: [`strip_test_mods`]
/// removes only module bodies, so such a site is counted and the
/// census fails rather than quietly widening its own scope.
fn calls_in(text: &str) -> Vec<(usize, String)> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while let Some(rel) = text[i..].find("decide_flagged") {
        let at = i + rel;
        i = at + "decide_flagged".len();
        // Not a longer identifier ending in this name, and not the
        // definition (`fn decide_flagged<T: Decide>(`, whose next
        // character is `<`).
        let prev_ok = at == 0 || {
            let p = bytes[at - 1];
            !(p.is_ascii_alphanumeric() || p == b'_')
        };
        if !prev_ok {
            continue;
        }
        let rest = &text[i..];
        let open = rest.len() - rest.trim_start().len();
        if rest[open..].starts_with('(') {
            let line = text[..at].lines().count();
            // Doc and line comments mention the name in prose.
            let line_start = text[..at].rfind('\n').map_or(0, |n| n + 1);
            if text[line_start..at].trim_start().starts_with("//") {
                continue;
            }
            out.push((line, args_of(&text[i + open + 1..])));
            i += open + 1;
        }
    }
    out.into_iter()
        .map(|(line, args)| (line, fourth_argument(&args)))
        .collect()
}

/// The raw text of a call's argument list, from just after `(` to its
/// matching `)`. Tracks string and char literals so a comma or paren
/// inside a predicate name does not split the list, and strips line
/// comments so one inside a multi-line call does not either.
fn args_of(after_open: &str) -> String {
    let mut depth = 1usize;
    let mut out = String::new();
    let mut chars = after_open.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' => {
                out.push(c);
                while let Some(d) = chars.next() {
                    out.push(d);
                    if d == '\\' {
                        if let Some(e) = chars.next() {
                            out.push(e);
                        }
                    } else if d == '"' {
                        break;
                    }
                }
            }
            '/' if chars.peek() == Some(&'/') => {
                for d in chars.by_ref() {
                    if d == '\n' {
                        out.push('\n');
                        break;
                    }
                }
            }
            '(' | '[' | '{' => {
                depth += 1;
                out.push(c);
            }
            ')' | ']' | '}' => {
                depth -= 1;
                if depth == 0 {
                    return out;
                }
                out.push(c);
            }
            _ => out.push(c),
        }
    }
    panic!("unterminated decide_flagged argument list: {after_open:.120}");
}

/// The fourth top-level argument, which must be a string literal.
fn fourth_argument(args: &str) -> String {
    let mut depth = 0usize;
    let mut parts = vec![String::new()];
    let mut chars = args.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' => {
                parts.last_mut().unwrap().push(c);
                while let Some(d) = chars.next() {
                    parts.last_mut().unwrap().push(d);
                    if d == '\\' {
                        if let Some(e) = chars.next() {
                            parts.last_mut().unwrap().push(e);
                        }
                    } else if d == '"' {
                        break;
                    }
                }
            }
            '(' | '[' | '{' | '<' => {
                depth += 1;
                parts.last_mut().unwrap().push(c);
            }
            ')' | ']' | '}' | '>' => {
                depth = depth.saturating_sub(1);
                parts.last_mut().unwrap().push(c);
            }
            ',' if depth == 0 => parts.push(String::new()),
            _ => parts.last_mut().unwrap().push(c),
        }
    }
    let fourth = parts
        .get(3)
        .unwrap_or_else(|| panic!("decide_flagged call with fewer than 4 arguments: {args:.200}"))
        .trim();
    fourth
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .unwrap_or_else(|| {
            panic!(
                "a decide_flagged site cites its ledger row as `{fourth}`, not a string literal. \
                 The census can only verify literals; give the site its row directly, or teach \
                 this test to resolve the indirection — do not leave it unchecked."
            )
        })
        .to_string()
}

/// Blanks out `#[cfg(test)]` module bodies, preserving line numbering.
///
/// A `src/` tree is the census's proxy for "shipped", and the proxy is
/// wrong for in-file test modules: they live in `src/` and ship in no
/// build. The fixture convention makes the difference visible — a
/// fixture's `ledger_row` is a prose reason, not a row code — but the
/// COUNT would still move, so the proxy is corrected here rather than
/// leaned on.
///
/// **The cut is by indentation, not by brace matching**, and that is
/// deliberate: a brace scanner has to understand string literals,
/// `'static` lifetimes and block comments before it can be trusted,
/// whereas every file this walks is rustfmt-clean (the pre-push hook
/// enforces it), so a test module's closing brace is the next line
/// equal to its own indent plus `}`. What the cut does NOT remove: a
/// `#[cfg(test)]` on a **function** or a `use` rather than a module,
/// and a module gated by any other spelling (`#[cfg(all(test, …))]`).
/// Both leave their calls counted, so the census fails loudly rather
/// than quietly widening its own scope.
fn strip_test_mods(text: &str) -> String {
    let lines: Vec<&str> = text.lines().collect();
    let mut keep: Vec<String> = lines.iter().map(|l| (*l).to_string()).collect();
    let mut i = 0;
    while i < lines.len() {
        let indent = lines[i].len() - lines[i].trim_start().len();
        if lines[i].trim() == "#[cfg(test)]"
            && lines
                .get(i + 1)
                .is_some_and(|l| l.trim_start().starts_with("mod ") && l.trim_end().ends_with('{'))
        {
            let close = format!("{}}}", " ".repeat(indent));
            let mut j = i + 2;
            while j < lines.len() && lines[j].trim_end() != close {
                j += 1;
            }
            assert!(
                j < lines.len(),
                "a #[cfg(test)] mod at line {} has no closing brace at its own indent — the \
                 source is not rustfmt-clean and this census cannot cut it",
                i + 1
            );
            for line in keep.iter_mut().take(j + 1).skip(i) {
                line.clear();
            }
            i = j + 1;
        } else {
            i += 1;
        }
    }
    keep.join("\n")
}

fn count_in_tree(dir: &Path, hits: &mut Vec<Site>) {
    for entry in std::fs::read_dir(dir).expect("readable src tree") {
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            count_in_tree(&path, hits);
        } else if path.extension().is_some_and(|e| e == "rs") {
            let text = std::fs::read_to_string(&path).expect("readable source file");
            for (line, ledger_row) in calls_in(&strip_test_mods(&text)) {
                hits.push(Site {
                    file: path.clone(),
                    line,
                    ledger_row,
                });
            }
        }
    }
}

fn shipped_sites() -> (PathBuf, Vec<Site>) {
    // geom-core sits at <workspace>/crates/geom-core.
    let crates_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates dir")
        .to_path_buf();
    let mut hits = Vec::new();
    for entry in std::fs::read_dir(&crates_root).expect("crates dir listing") {
        let src = entry.expect("dir entry").path().join("src");
        if src.is_dir() {
            count_in_tree(&src, &mut hits);
        }
    }
    hits.sort_by(|a, b| (&a.file, a.line).cmp(&(&b.file, b.line)));
    (crates_root, hits)
}

#[test]
fn shipped_decide_flagged_sites_match_the_ledger() {
    let (_, hits) = shipped_sites();
    assert_eq!(
        hits.len(),
        LEDGER_FLAGGED_SITES,
        "shipped decide_flagged sites diverged from the ledger's inventory \
         (docs/predicate-dimension-audit.md, clause-(i) section; issue #214). \
         A new site needs a ledger row FIRST, then this count moves with it. \
         Sites found: {hits:#?}"
    );
}

#[test]
fn every_shipped_site_cites_a_ledger_row_that_exists() {
    let (crates_root, hits) = shipped_sites();
    let audit = crates_root
        .parent()
        .expect("workspace root")
        .join("docs/predicate-dimension-audit.md");
    let text = std::fs::read_to_string(&audit).expect("readable predicate-dimension audit");
    // Rows are `- **F13** …` bullets; F1's heading carries a
    // parenthetical before the closing `**`, so the number is read up
    // to the first non-digit.
    let rows: BTreeSet<String> = text
        .lines()
        .filter_map(|l| l.strip_prefix("- **F"))
        .map(|r| {
            let digits: String = r.chars().take_while(char::is_ascii_digit).collect();
            format!("F{digits}")
        })
        .filter(|r| r.len() > 1)
        .collect();
    assert!(
        !rows.is_empty(),
        "no `- **FNN**` row bullets found in {}: the ledger's format changed and this check \
         became vacuous",
        audit.display()
    );
    for site in &hits {
        assert!(
            rows.contains(&site.ledger_row),
            "{}:{} cites ledger row `{}`, which {} does not have. The rule the parameter \
             stands for is that a flagged site is argued for in the audit; a citation that \
             resolves to nothing is a string. Rows present: {:?}",
            site.file.display(),
            site.line,
            site.ledger_row,
            audit.display(),
            rows
        );
    }
}
