//! The **large-K fragility lint** (M4 PR 8b, spec D3): scans fresh
//! K-telemetry CSVs (the `scripts/k_probe_sweep.sh` output — every
//! predicate decision of the Band 4 corpus + the demo scenes at the
//! recording scalar) and FLAGS margins that crowd a decision boundary.
//! **Advisory in its first iteration: the CI row prints flags and
//! never fails on them** (it fails only on harness breakage — missing
//! or malformed input).
//!
//! # What gets flagged
//!
//! 1. **In-band / invalid outcomes** — a recorded `indeterminate` is a
//!    margin INSIDE the ambiguity band `(ε, Kε)` (maximal fragility;
//!    the kernel refused typed), an `invalid` is a poisoned margin.
//! 2. **Band proximity** (the spec's "within 10^2 of the ambient band
//!    at ANY supported ε row" — the sweep runs all three supported ε
//!    rows, so every row is linted at its own recorded band):
//!    a definite non-zero margin within [`PROXIMITY_FACTOR`] of the
//!    escalation threshold (`|m| < 10² · Kε`), or a zero-classified
//!    margin within [`PROXIMITY_FACTOR`] below the coincidence
//!    threshold (`|m| > ε / 10²`).
//! 3. **Below the baseline floor** — a definite non-zero margin
//!    smaller than [`BASELINE_FLOOR_MARGIN`], the bottom edge of the
//!    committed baseline's ε-INDEPENDENT distribution (see "Threshold
//!    provenance").
//! 4. **Below the ε-coupled floor** — for the ε-coupled families
//!    ([`EPS_COUPLED_PREDICATES`]), whose margin is a headroom against
//!    an ε-scaled target rather than a model-scale distance: a definite
//!    margin below [`EPS_COUPLED_FLOOR_RATIO`] · ε. Those families are
//!    NOT subject to rules (2) or (3) — see "The ε-coupled families".
//!
//! Ratio rules (2), (3) and (4) apply only to samples deciding against an
//! AMBIENT band (`band_zero ≥` [`AMBIENT_BAND_MIN`]): the kernel also
//! records exact tie-break bands (e.g. `canonical_order_*` at
//! `band_zero = 5e-324`, `segment_straightness` at `1e-100`), which
//! are order/degeneracy decisions with their own scale, not
//! coincidence classifications — their margins are not commensurate
//! with the ε machinery this lint watches. Rule (1) is outcome-based
//! and exempt from the gate.
//!
//! # Threshold provenance (baseline: docs/k-report-data/m7-eps-*.csv.gz)
//!
//! Committed baseline: the M7 refresh sweep over the Band 4 corpus AND
//! the demo scenes — 1,792,902 / 1,792,926 / 1,792,950 samples at
//! ε ∈ {1e-6, 1e-9, 1e-12}, 233 distinct predicate names, generated by
//! `K_SWEEP_PREFIX=m7-eps- scripts/k_probe_sweep.sh docs/k-report-data
//! --gzip`. The M4 baseline these thresholds were first cut against
//! (`m4-eps-*`, 2,562,157/row) and the M5 snapshot (`m5-eps-*`,
//! 1,758,387/row) stay committed as the durable record.
//!
//! The row counts are NOT equal across ε any more (+24/row): the
//! ε-coupled family below samples more often at tighter ε (K-REPORT
//! Finding M5-1). Everything else is geometry, not tolerance.
//!
//! The ε-INDEPENDENT distribution is still sharply bimodal (full
//! histogram: docs/K-REPORT.md, M7 addendum) — 1,348,461 ambient
//! definite samples, identical at all three rows:
//!
//! - zero-classified cluster: |m| ≤ 5.329e-15 (worst: `pm_census_ee_span`
//!   on demo/az) — unmoved since M4;
//! - definite cluster: |m| ≥ 4.7965e-5 (worst: `volume_backstop` on
//!   corpus/die_pips and corpus/die_composed — the pip cavities' volume
//!   slack metered as a mean boundary displacement, a real 48 µm
//!   quantity);
//! - the ~10.0-decade gap between them is EMPTY once the ε-coupled
//!   family is set aside: 0 indeterminate, 0 invalid, 0 samples.
//!
//! [`BASELINE_FLOOR_MARGIN`] is the **0th percentile** of that
//! ε-independent definite population (observed minimum 4.7965e-5,
//! rounded down to 4.0e-5 — 16.6% of headroom).
//! Percentile choice rationale (spec: "REPORT the percentile choice"),
//! re-argued against the M7 distribution: P0.001 = 1.4916e-4 already
//! strands the die/die_pips/die_composed backstop margins; P0.01 =
//! 3.8393e-3 strands the whole `volume_backstop` family plus
//! `pm_census_ee_gap` (M4's old floor) and `split_bisector_side`;
//! P0.1 = 2.4e-2 and P1 = 6.25e-2 strand most of the corpus's
//! millimetre-scale work. Any P > 0 is permanent noise with no added
//! signal, because the 10-decade empty gap makes the population edge
//! itself the maximally informative threshold: a NEW margin below the
//! floor sits in the no-man's land between honest coincidence and
//! honest feature — exactly the #99 class (margin 2.315e-6: in-band at
//! ε = 1e-6, and below this floor at EVERY supported ε row, with 1.2
//! decades to spare).
//!
//! Headroom is wider than M4's ~11% on purpose: M4's floor sample was a
//! rigid feature gap, while `volume_backstop`'s margin is ΔV/(A+A) — a
//! smeared quantity that moves with how fine the model's detail is
//! relative to its surface area, so it deserves a wider skirt.
//!
//! The floor compares the margin in its own units (meters for the
//! geometric predicates; the few radian·arm-metered angular margins
//! share the numeric floor — their baseline minima sit far above it).
//!
//! # The ε-coupled families (rule 4)
//!
//! [`EPS_COUPLED_PREDICATES`] lists the predicates whose recorded
//! margin is a headroom against an ε-SCALED target rather than a
//! model-scale distance. Today that is exactly one:
//! `props_quad_converged`, the adaptive-quadrature stopping test — it
//! records `1024·ε − width`, so its margin shrinks with ε BY
//! CONSTRUCTION (baseline minima 8.3952e-4 / 1.6467e-7 / 3.3595e-10 at
//! 1e-6 / 1e-9 / 1e-12).
//!
//! No fixed metre floor can be both clean at 1e-12 and informative, so
//! this family is taken out from under rule (3). It is taken out from
//! under rule (2) as well, and that is the honest half of the ruling:
//! its entire operating range is (0, 1024·ε] = (0, 102.4·Kε] at the
//! ratified K = 10, so "within 10² of Kε" is its PERMANENT state and
//! carries no information — rule (2) applied to it is a tautology, not
//! a finding. Muting it is not an option either, so rule (4) is rule
//! (2) RECALIBRATED to the family's own scale: flag when the headroom
//! falls below [`EPS_COUPLED_FLOOR_RATIO`] · ε = 15·Kε, the bottom ~15%
//! of the range. That is a real fragility statement — the stopping
//! round cleared the target by so little that at the interval scalar
//! the enclosure could straddle and escalate.
//!
//! [`EPS_COUPLED_FLOOR_RATIO`] = 1.5e2 is the P0 of the baseline's own
//! |m|/ε population (minimum 164.674, at demo/tiltedcut on the 1e-9
//! row; the other rows sit at 839.524 and 335.953) rounded down with
//! 8.9% of headroom. Its semantics DIFFER from the metre floor's and
//! the difference is worth naming: this is a calibrated proximity
//! rule on a BOUNDED statistic, not the edge of an empty gap. The
//! quadrature loop stops at the first round whose width clears the
//! target and widths fall ~8× per round, so the headroom has no
//! structural lower bound — a face whose width lands just under target
//! WILL trip rule (4). That is the intended signal, not a false
//! positive: it is the same decision fragility rule (2) exists to name,
//! measured where this family actually lives.
//!
//! Membership is an explicit allow-list, never inferred. A NEW
//! ε-coupled predicate is not on it, so it stays under rules (2) and
//! (3) and flags loudly until someone rules on it — the fail-loud
//! direction.

/// Ratio rules apply only to ambient (ε-scale) bands; the exact
/// tie-break bands the kernel also records are 5e-324 / 1e-100 —
/// dozens of decades below any supported ε (1e-6 … 1e-12).
pub const AMBIENT_BAND_MIN: f64 = 1e-13;

/// "Within 10^2 of the band": the spec's proximity factor (D3).
pub const PROXIMITY_FACTOR: f64 = 1e2;

/// The baseline distribution's bottom edge (provenance in the module
/// docs — the M7 baseline's smallest ε-INDEPENDENT definite margin
/// 4.7965e-5, P0, rounded down to 4.0e-5 so the baseline itself lints
/// clean with 16.6% of headroom).
pub const BASELINE_FLOOR_MARGIN: f64 = 4.0e-5;

/// The ε-coupled families: predicates whose recorded margin is a
/// headroom against an ε-scaled target, not a model-scale distance.
/// Exempt from rules (2) and (3), watched by rule (4) instead — the
/// argument is in the module docs ("The ε-coupled families"). An
/// explicit allow-list on purpose: a new ε-coupled predicate is NOT on
/// it and keeps flagging under the metre rules until someone rules.
pub const EPS_COUPLED_PREDICATES: [&str; 1] = ["props_quad_converged"];

/// Rule (4)'s floor for [`EPS_COUPLED_PREDICATES`], in units of ε:
/// P0 of the baseline's |m|/ε population (minimum 164.674), rounded
/// down to 1.5e2 = 15·Kε with 8.9% of headroom.
pub const EPS_COUPLED_FLOOR_RATIO: f64 = 1.5e2;

/// Whether `predicate` is one of the [`EPS_COUPLED_PREDICATES`].
#[must_use]
pub fn is_eps_coupled(predicate: &str) -> bool {
    EPS_COUPLED_PREDICATES.contains(&predicate)
}

/// Why a sample was flagged.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    /// Outcome `indeterminate`: the margin landed INSIDE the band.
    InBand,
    /// Outcome `invalid`: poisoned margin.
    Invalid,
    /// Definite margin within [`PROXIMITY_FACTOR`] of `band_escalate`.
    NearBandAbove,
    /// Zero-classified margin within [`PROXIMITY_FACTOR`] below
    /// `band_zero`.
    NearBandBelow,
    /// Definite margin below [`BASELINE_FLOOR_MARGIN`].
    BelowBaselineFloor,
    /// An [`EPS_COUPLED_PREDICATES`] margin below
    /// [`EPS_COUPLED_FLOOR_RATIO`] · ε.
    BelowEpsCoupledFloor,
}

impl core::fmt::Display for Reason {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let s = match self {
            Reason::InBand => "IN the ambiguity band (indeterminate outcome)",
            Reason::Invalid => "invalid (poisoned) margin",
            Reason::NearBandAbove => "definite within 10^2 of the escalation threshold",
            Reason::NearBandBelow => "zero-classified within 10^2 of the coincidence threshold",
            Reason::BelowBaselineFloor => "definite below the baseline distribution's floor (4e-5)",
            Reason::BelowEpsCoupledFloor => {
                "ε-coupled headroom below the ε-relative floor (1.5e2·ε)"
            }
        };
        f.write_str(s)
    }
}

/// One flagged CSV row.
#[derive(Debug, Clone)]
pub struct Flag {
    /// 1-based line number in the input.
    pub line: usize,
    pub shape: String,
    pub predicate: String,
    pub margin: f64,
    pub band_zero: f64,
    pub reasons: Vec<Reason>,
}

/// A malformed input line (harness breakage — this FAILS the CI row;
/// findings never do).
#[derive(Debug)]
pub struct ParseError {
    pub line: usize,
    pub text: String,
}

/// Lint verdict for one parsed sample; empty when the sample is
/// clean. Exposed for the litmus test, which synthesizes the #99
/// datum against every supported ε row's band.
///
/// `predicate` selects the rule set: the [`EPS_COUPLED_PREDICATES`]
/// answer to rule (4) instead of rules (2) and (3) — module docs.
#[must_use]
pub fn lint_sample(
    predicate: &str,
    margin: f64,
    band_zero: f64,
    band_escalate: f64,
    outcome: &str,
) -> Vec<Reason> {
    let mut reasons = Vec::new();
    let m = margin.abs();
    match outcome {
        "indeterminate" => reasons.push(Reason::InBand),
        "invalid" => reasons.push(Reason::Invalid),
        "zero" if band_zero >= AMBIENT_BAND_MIN => {
            // Coincidence proximity is the same question in the same
            // units for every family: a zero classification is a
            // decision against ε itself, ε-coupled or not.
            if m > band_zero / PROXIMITY_FACTOR {
                reasons.push(Reason::NearBandBelow);
            }
        }
        "positive" | "negative" if band_zero >= AMBIENT_BAND_MIN => {
            if is_eps_coupled(predicate) {
                if m < EPS_COUPLED_FLOOR_RATIO * band_zero {
                    reasons.push(Reason::BelowEpsCoupledFloor);
                }
            } else {
                if m < band_escalate * PROXIMITY_FACTOR {
                    reasons.push(Reason::NearBandAbove);
                }
                if m < BASELINE_FLOOR_MARGIN {
                    reasons.push(Reason::BelowBaselineFloor);
                }
            }
        }
        _ => {}
    }
    reasons
}

/// Lints a whole CSV (the sweep's format:
/// `shape,predicate,margin,band_zero,band_escalate,outcome`).
///
/// # Errors
///
/// The first malformed line — bad column count, unparseable float, or
/// an UNKNOWN outcome string (harness breakage; findings never error).
pub fn lint_csv(text: &str) -> Result<(usize, Vec<Flag>), ParseError> {
    let mut flags = Vec::new();
    let mut scanned = 0usize;
    for (i, line) in text.lines().enumerate() {
        if i == 0 {
            if line != "shape,predicate,margin,band_zero,band_escalate,outcome" {
                return Err(ParseError {
                    line: 1,
                    text: line.to_string(),
                });
            }
            continue;
        }
        if line.is_empty() {
            continue;
        }
        let err = || ParseError {
            line: i + 1,
            text: line.to_string(),
        };
        let mut it = line.split(',');
        let (Some(shape), Some(pred), Some(m), Some(bz), Some(be), Some(out), None) = (
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
        ) else {
            return Err(err());
        };
        let margin: f64 = m.parse().map_err(|_| err())?;
        let band_zero: f64 = bz.parse().map_err(|_| err())?;
        let band_escalate: f64 = be.parse().map_err(|_| err())?;
        // An unknown outcome string is harness breakage, exactly like
        // a malformed float: scoring it silently CLEAN would let a
        // sweep-format drift disarm the whole lint (review MIN-2).
        if !matches!(
            out,
            "zero" | "positive" | "negative" | "indeterminate" | "invalid"
        ) {
            return Err(err());
        }
        scanned += 1;
        let reasons = lint_sample(pred, margin, band_zero, band_escalate, out);
        if !reasons.is_empty() {
            flags.push(Flag {
                line: i + 1,
                shape: shape.to_string(),
                predicate: pred.to_string(),
                margin,
                band_zero,
                reasons,
            });
        }
    }
    Ok((scanned, flags))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_definite_and_zero_pass() {
        // Baseline-shaped samples: definite far above the band, zero at
        // machine noise.
        assert!(lint_sample("p", 2.0, 1e-9, 1e-8, "positive").is_empty());
        assert!(lint_sample("p", -2.0, 1e-9, 1e-8, "negative").is_empty());
        assert!(lint_sample("p", 1e-16, 1e-9, 1e-8, "zero").is_empty());
    }

    #[test]
    fn in_band_and_invalid_always_flag() {
        assert_eq!(
            lint_sample("p", 2.3e-6, 1e-6, 1e-5, "indeterminate"),
            vec![Reason::InBand]
        );
        assert_eq!(
            lint_sample("p", f64::NAN, 1e-9, 1e-8, "invalid"),
            vec![Reason::Invalid]
        );
        // The gate does NOT exempt outcome-based flags.
        assert_eq!(
            lint_sample("p", 0.0, 5e-324, 1e-323, "invalid"),
            vec![Reason::Invalid]
        );
        // …nor does the ε-coupled allow-list: rule (4) replaces the
        // two RATIO rules only, never the outcome rule.
        assert_eq!(
            lint_sample("props_quad_converged", 5e-9, 1e-9, 1e-8, "indeterminate"),
            vec![Reason::InBand]
        );
    }

    #[test]
    fn proximity_flags_both_sides_of_the_band() {
        // Definite 1.5 decades above Kε: flagged (and it is also below
        // the baseline floor).
        assert_eq!(
            lint_sample("p", 3e-7, 1e-9, 1e-8, "positive"),
            vec![Reason::NearBandAbove, Reason::BelowBaselineFloor]
        );
        // Zero half a decade below ε: flagged.
        assert_eq!(
            lint_sample("p", 3e-10, 1e-9, 1e-8, "zero"),
            vec![Reason::NearBandBelow]
        );
    }

    #[test]
    fn floor_flags_the_gap_population() {
        // A margin in the bimodal gap, definite at 1e-9 — exactly the
        // #99 class. (Not near the band: 2.315e-6 > 10²·Kε = 1e-6.)
        assert_eq!(
            lint_sample("p", 2.315e-6, 1e-9, 1e-8, "positive"),
            vec![Reason::BelowBaselineFloor]
        );
        // At the M7 baseline's observed ε-independent minimum
        // (`volume_backstop`, corpus/die_pips): clean at the two rows
        // where the band leaves room — the floor is P0 rounded DOWN.
        assert!(lint_sample("volume_backstop", 4.7965e-5, 1e-9, 1e-8, "positive").is_empty());
        assert!(lint_sample("volume_backstop", 4.7965e-5, 1e-12, 1e-11, "positive").is_empty());
        // M4's old floor sample is now ~1.6 decades ABOVE the floor:
        // clean, and no longer the bottom of the distribution.
        assert!(lint_sample("pm_census_ee_gap", 1.689e-3, 1e-6, 1e-5, "positive").is_empty());
        // Just under the floor still flags.
        assert_eq!(
            lint_sample("p", 3.9e-5, 1e-12, 1e-11, "positive"),
            vec![Reason::BelowBaselineFloor]
        );
    }

    #[test]
    fn eps_coupled_family_answers_to_the_eps_relative_floor_only() {
        assert!(is_eps_coupled("props_quad_converged"));
        assert!(!is_eps_coupled("volume_backstop"));
        // The three baseline minima of `props_quad_converged`
        // (8.3952e-4 / 1.6467e-7 / 3.3595e-10 at 1e-6 / 1e-9 / 1e-12):
        // all CLEAN under rule (4), all of them would have flagged
        // under the metre floor, and the 1e-9/1e-12 ones under rule (2)
        // as well.
        for (m, zero, esc) in [
            (8.3952e-4, 1e-6, 1e-5),
            (1.6467e-7, 1e-9, 1e-8),
            (3.3595e-10, 1e-12, 1e-11),
        ] {
            assert!(
                lint_sample("props_quad_converged", m, zero, esc, "positive").is_empty(),
                "baseline ε-coupled minimum {m:e} must lint clean at ε={zero:e}"
            );
            assert!(
                !lint_sample("volume_backstop", m, zero, esc, "positive").is_empty(),
                "the SAME margin under the metre rules must flag"
            );
        }
        // Below 1.5e2·ε: rule (4) fires, and only rule (4).
        assert_eq!(
            lint_sample("props_quad_converged", 1.4e-7, 1e-9, 1e-8, "positive"),
            vec![Reason::BelowEpsCoupledFloor]
        );
        // The convergence target itself (1024·ε) is the family's
        // ceiling and sits just above rule (2)'s 10²·Kε — the
        // tautology rule (4) replaces.
        assert!(lint_sample("props_quad_converged", 1.024e-9, 1e-12, 1e-11, "positive").is_empty());
    }

    #[test]
    fn exact_tie_break_bands_are_exempt_from_ratio_rules() {
        // canonical_order-style sample: tiny coordinate delta against
        // the 5e-324 band — an order decision, not a coincidence one.
        assert!(lint_sample("p", 1e-4, 5e-324, 1e-323, "positive").is_empty());
        // segment_straightness-style exact zero.
        assert!(lint_sample("p", 0.0, 1e-100, 1e-99, "zero").is_empty());
    }

    #[test]
    fn csv_parses_flags_and_refuses_malformed() {
        let csv = "shape,predicate,margin,band_zero,band_escalate,outcome\n\
                   demo/x,p1,2e0,1e-9,1e-8,positive\n\
                   demo/x,p2,2.315e-6,1e-6,9.999999999999999e-6,indeterminate\n";
        let (scanned, flags) = lint_csv(csv).expect("valid csv");
        assert_eq!(scanned, 2);
        assert_eq!(flags.len(), 1);
        assert_eq!(flags[0].predicate, "p2");
        assert_eq!(flags[0].reasons, vec![Reason::InBand]);
        assert!(lint_csv("bad header\n").is_err());
        // MIN-2 pin: a typo'd outcome must FAIL the row, not score
        // silently clean.
        assert!(
            lint_csv(
                "shape,predicate,margin,band_zero,band_escalate,outcome\nx,y,2e0,1e-9,1e-8,positve\n"
            )
            .is_err()
        );
        assert!(
            lint_csv(
                "shape,predicate,margin,band_zero,band_escalate,outcome\nx,y,notafloat,1,1,zero\n"
            )
            .is_err()
        );
    }
}
