//! The **large-K fragility lint** (M4 PR 8b, spec D3): scans fresh
//! K-telemetry CSVs (the `scripts/k_probe_sweep.sh` output — every
//! predicate decision of the Band 4 corpus + the demo scenes at the
//! recording scalar) and FLAGS margins that crowd a decision boundary.
//! **Advisory in its first iteration: the CI row prints flags and
//! never fails on them** (it fails only on harness breakage — missing
//! or malformed input).
//!
//! # What gets flagged
//!
//! 1. **In-band / invalid outcomes** — a recorded `indeterminate` is a
//!    margin INSIDE the ambiguity band `(ε, Kε)` (maximal fragility;
//!    the kernel refused typed), an `invalid` is a poisoned margin.
//! 2. **Band proximity** (the spec's "within 10^2 of the ambient band
//!    at ANY supported ε row" — the sweep runs all three supported ε
//!    rows, so every row is linted at its own recorded band):
//!    a definite non-zero margin within [`PROXIMITY_FACTOR`] of the
//!    escalation threshold (`|m| < 10² · Kε`), or a zero-classified
//!    margin within [`PROXIMITY_FACTOR`] below the coincidence
//!    threshold (`|m| > ε / 10²`).
//! 3. **Below the baseline floor** — a definite non-zero margin
//!    smaller than [`BASELINE_FLOOR_MARGIN`], the bottom edge of the
//!    committed baseline distribution (see "Threshold provenance").
//!
//! Ratio rules (2) and (3) apply only to samples deciding against an
//! AMBIENT band (`band_zero ≥` [`AMBIENT_BAND_MIN`]): the kernel also
//! records exact tie-break bands (e.g. `canonical_order_*` at
//! `band_zero = 5e-324`, `segment_straightness` at `1e-100`), which
//! are order/degeneracy decisions with their own scale, not
//! coincidence classifications — their margins are not commensurate
//! with the ε machinery this lint watches. Rule (1) is outcome-based
//! and exempt from the gate.
//!
//! # Threshold provenance (baseline: docs/k-report-data/m4-eps-*.csv.gz)
//!
//! Committed baseline: the M4 PR 8b probe run over the Band 4 corpus
//! AND the demo scenes — 2,562,157 samples per ε row at ε ∈ {1e-6,
//! 1e-9, 1e-12} (row counts identical across ε; margins are geometry,
//! not tolerance), generated by `scripts/k_probe_sweep.sh
//! docs/k-report-data --gzip` at the PR 8b head. The distribution is
//! sharply bimodal (full histogram: docs/K-REPORT.md, M4 addendum):
//!
//! - zero-classified cluster: |m| ≤ 5.33e-15 (worst: `pm_census_ee_span`
//!   on demo/az) — ≥ 2.3 decades below even the tightest row's ε;
//! - definite cluster: |m| ≥ 1.689e-3 (worst: `pm_census_ee_gap` on
//!   demo/az) — ≥ 3.2 decades above even the loosest row's Kε;
//! - the ~12-decade gap between them is EMPTY: 0 indeterminate,
//!   0 invalid, nothing near either band edge.
//!
//! [`BASELINE_FLOOR_MARGIN`] is the **0th percentile** (the observed
//! minimum, 1.689e-3, rounded down one significant figure to 1.5e-3).
//! Percentile choice rationale (spec: "REPORT the percentile choice"):
//! any P > 0 would flag the baseline's own bottom tail on every
//! advisory run (P0.01 ≈ 7.8e3·ε already strands the 240 real az
//! census margins in decade 3) — permanent noise, no added signal,
//! because the 12-decade gap makes the population edge itself the
//! maximally informative threshold. A NEW margin below the floor is a
//! margin in the no-man's land between honest coincidence and honest
//! feature — exactly the #99 class (margin 2.315e-6: in-band at
//! ε = 1e-6, and below this floor at EVERY supported ε row).
//!
//! The floor compares the margin in its own units (meters for the
//! geometric predicates; the few radian·arm-metered angular margins
//! share the numeric floor — their baseline minima sit far above it).

/// Ratio rules apply only to ambient (ε-scale) bands; the exact
/// tie-break bands the kernel also records are 5e-324 / 1e-100 —
/// dozens of decades below any supported ε (1e-6 … 1e-12).
pub const AMBIENT_BAND_MIN: f64 = 1e-13;

/// "Within 10^2 of the band": the spec's proximity factor (D3).
pub const PROXIMITY_FACTOR: f64 = 1e2;

/// The baseline distribution's bottom edge (provenance in the module
/// docs — the M4 baseline's smallest definite margin 1.689e-3, P0,
/// rounded down to one significant figure so the baseline itself
/// lints clean with honest headroom).
pub const BASELINE_FLOOR_MARGIN: f64 = 1.5e-3;

/// Why a sample was flagged.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    /// Outcome `indeterminate`: the margin landed INSIDE the band.
    InBand,
    /// Outcome `invalid`: poisoned margin.
    Invalid,
    /// Definite margin within [`PROXIMITY_FACTOR`] of `band_escalate`.
    NearBandAbove,
    /// Zero-classified margin within [`PROXIMITY_FACTOR`] below
    /// `band_zero`.
    NearBandBelow,
    /// Definite margin below [`BASELINE_FLOOR_MARGIN`].
    BelowBaselineFloor,
}

impl core::fmt::Display for Reason {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let s = match self {
            Reason::InBand => "IN the ambiguity band (indeterminate outcome)",
            Reason::Invalid => "invalid (poisoned) margin",
            Reason::NearBandAbove => "definite within 10^2 of the escalation threshold",
            Reason::NearBandBelow => "zero-classified within 10^2 of the coincidence threshold",
            Reason::BelowBaselineFloor => {
                "definite below the baseline distribution's floor (1.5e-3)"
            }
        };
        f.write_str(s)
    }
}

/// One flagged CSV row.
#[derive(Debug, Clone)]
pub struct Flag {
    /// 1-based line number in the input.
    pub line: usize,
    pub shape: String,
    pub predicate: String,
    pub margin: f64,
    pub band_zero: f64,
    pub reasons: Vec<Reason>,
}

/// A malformed input line (harness breakage — this FAILS the CI row;
/// findings never do).
#[derive(Debug)]
pub struct ParseError {
    pub line: usize,
    pub text: String,
}

/// Lint verdict for one parsed sample; `None` when the sample is
/// clean. Exposed for the litmus test, which synthesizes the #99
/// datum against every supported ε row's band.
#[must_use]
pub fn lint_sample(margin: f64, band_zero: f64, band_escalate: f64, outcome: &str) -> Vec<Reason> {
    let mut reasons = Vec::new();
    let m = margin.abs();
    match outcome {
        "indeterminate" => reasons.push(Reason::InBand),
        "invalid" => reasons.push(Reason::Invalid),
        "zero" if band_zero >= AMBIENT_BAND_MIN => {
            if m > band_zero / PROXIMITY_FACTOR {
                reasons.push(Reason::NearBandBelow);
            }
        }
        "positive" | "negative" if band_zero >= AMBIENT_BAND_MIN => {
            if m < band_escalate * PROXIMITY_FACTOR {
                reasons.push(Reason::NearBandAbove);
            }
            if m < BASELINE_FLOOR_MARGIN {
                reasons.push(Reason::BelowBaselineFloor);
            }
        }
        _ => {}
    }
    reasons
}

/// Lints a whole CSV (the sweep's format:
/// `shape,predicate,margin,band_zero,band_escalate,outcome`).
///
/// # Errors
///
/// The first malformed line (harness breakage).
pub fn lint_csv(text: &str) -> Result<(usize, Vec<Flag>), ParseError> {
    let mut flags = Vec::new();
    let mut scanned = 0usize;
    for (i, line) in text.lines().enumerate() {
        if i == 0 {
            if line != "shape,predicate,margin,band_zero,band_escalate,outcome" {
                return Err(ParseError {
                    line: 1,
                    text: line.to_string(),
                });
            }
            continue;
        }
        if line.is_empty() {
            continue;
        }
        let err = || ParseError {
            line: i + 1,
            text: line.to_string(),
        };
        let mut it = line.split(',');
        let (Some(shape), Some(pred), Some(m), Some(bz), Some(be), Some(out), None) = (
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
        ) else {
            return Err(err());
        };
        let margin: f64 = m.parse().map_err(|_| err())?;
        let band_zero: f64 = bz.parse().map_err(|_| err())?;
        let band_escalate: f64 = be.parse().map_err(|_| err())?;
        scanned += 1;
        let reasons = lint_sample(margin, band_zero, band_escalate, out);
        if !reasons.is_empty() {
            flags.push(Flag {
                line: i + 1,
                shape: shape.to_string(),
                predicate: pred.to_string(),
                margin,
                band_zero,
                reasons,
            });
        }
    }
    Ok((scanned, flags))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_definite_and_zero_pass() {
        // Baseline-shaped samples: definite far above the band, zero at
        // machine noise.
        assert!(lint_sample(2.0, 1e-9, 1e-8, "positive").is_empty());
        assert!(lint_sample(-2.0, 1e-9, 1e-8, "negative").is_empty());
        assert!(lint_sample(1e-16, 1e-9, 1e-8, "zero").is_empty());
    }

    #[test]
    fn in_band_and_invalid_always_flag() {
        assert_eq!(
            lint_sample(2.3e-6, 1e-6, 1e-5, "indeterminate"),
            vec![Reason::InBand]
        );
        assert_eq!(
            lint_sample(f64::NAN, 1e-9, 1e-8, "invalid"),
            vec![Reason::Invalid]
        );
        // The gate does NOT exempt outcome-based flags.
        assert_eq!(
            lint_sample(0.0, 5e-324, 1e-323, "invalid"),
            vec![Reason::Invalid]
        );
    }

    #[test]
    fn proximity_flags_both_sides_of_the_band() {
        // Definite 1.5 decades above Kε: flagged (and it is also below
        // the baseline floor).
        assert_eq!(
            lint_sample(3e-7, 1e-9, 1e-8, "positive"),
            vec![Reason::NearBandAbove, Reason::BelowBaselineFloor]
        );
        // Zero half a decade below ε: flagged.
        assert_eq!(
            lint_sample(3e-10, 1e-9, 1e-8, "zero"),
            vec![Reason::NearBandBelow]
        );
    }

    #[test]
    fn floor_flags_the_gap_population() {
        // A margin in the bimodal gap, definite at 1e-9 — exactly the
        // #99 class.
        assert_eq!(
            lint_sample(2.315e-6, 1e-9, 1e-8, "positive"),
            vec![Reason::BelowBaselineFloor]
        );
        // At the observed baseline minimum: clean (the floor is P0
        // rounded DOWN — the baseline lints clean).
        assert!(lint_sample(1.689e-3, 1e-6, 1e-5, "positive").is_empty());
    }

    #[test]
    fn exact_tie_break_bands_are_exempt_from_ratio_rules() {
        // canonical_order-style sample: tiny coordinate delta against
        // the 5e-324 band — an order decision, not a coincidence one.
        assert!(lint_sample(1e-4, 5e-324, 1e-323, "positive").is_empty());
        // segment_straightness-style exact zero.
        assert!(lint_sample(0.0, 1e-100, 1e-99, "zero").is_empty());
    }

    #[test]
    fn csv_parses_flags_and_refuses_malformed() {
        let csv = "shape,predicate,margin,band_zero,band_escalate,outcome\n\
                   demo/x,p1,2e0,1e-9,1e-8,positive\n\
                   demo/x,p2,2.315e-6,1e-6,9.999999999999999e-6,indeterminate\n";
        let (scanned, flags) = lint_csv(csv).expect("valid csv");
        assert_eq!(scanned, 2);
        assert_eq!(flags.len(), 1);
        assert_eq!(flags[0].predicate, "p2");
        assert_eq!(flags[0].reasons, vec![Reason::InBand]);
        assert!(lint_csv("bad header\n").is_err());
        assert!(
            lint_csv(
                "shape,predicate,margin,band_zero,band_escalate,outcome\nx,y,notafloat,1,1,zero\n"
            )
            .is_err()
        );
    }
}
