//! The **large-K fragility lint** (M4 PR 8b, spec D3): scans fresh
//! K-telemetry CSVs (the `scripts/k_probe_sweep.sh` output — every
//! predicate decision of the Band 4 corpus + the demo scenes at the
//! recording scalar) and FLAGS margins that crowd a decision boundary.
//! **The CI row is a GATE: a finding fails it.** A firing lint is
//! evidence that the margin DISTRIBUTION moved — possibly that a
//! threshold or the baseline is stale — never a licence to nudge
//! geometry until the lint goes quiet; the CLI prints that discipline
//! and its recourse on every failure (`main.rs`). Harness breakage
//! (missing or malformed input) fails with its own distinct voice.
//!
//! # What gets flagged
//!
//! 1. **In-band / invalid outcomes** — a recorded `indeterminate` is a
//!    margin INSIDE the ambiguity band `(ε, Kε)` (maximal fragility;
//!    the kernel refused typed), an `invalid` is a poisoned margin.
//! 2. **Band proximity** (the spec's "within 10^2 of the ambient band
//!    at ANY supported ε row" — the sweep runs all three supported ε
//!    rows, so every row is linted at its own recorded band):
//!    a definite non-zero margin within [`PROXIMITY_FACTOR`] of the
//!    escalation threshold (`|m| < 10² · Kε`, **capped at**
//!    [`BASELINE_FLOOR_MARGIN`] — see "Rule (2)'s discrimination
//!    floor"), or a zero-classified margin within [`PROXIMITY_FACTOR`]
//!    below the coincidence threshold (`|m| > ε / 10²`).
//! 3. **Below the baseline floor** — a definite non-zero margin
//!    smaller than [`BASELINE_FLOOR_MARGIN`], the bottom edge of the
//!    committed baseline's ε-INDEPENDENT distribution (see "Threshold
//!    provenance").
//! 4. **Below the ε-coupled floor** — for the ε-coupled families
//!    ([`EPS_COUPLED_PREDICATES`]), whose margin is a headroom against
//!    an ε-scaled target rather than a model-scale distance: a definite
//!    margin below [`EPS_COUPLED_FLOOR_RATIO`] · ε. Those families are
//!    NOT subject to rules (2) or (3) — see "The ε-coupled families".
//!
//! Ratio rules (2), (3) and (4) apply only to samples deciding against an
//! AMBIENT band (`band_zero ≥` [`AMBIENT_BAND_MIN`]): the kernel also
//! records exact tie-break bands (e.g. `canonical_order_*` at
//! `band_zero = 5e-324`, `segment_straightness` at `1e-100`), which
//! are order/degeneracy decisions with their own scale, not
//! coincidence classifications — their margins are not commensurate
//! with the ε machinery this lint watches. Rule (1) is outcome-based
//! and exempt from that ambient-band guard.
//!
//! # Threshold provenance (baseline: docs/k-report-data/m7-eps-*.csv.gz)
//!
//! Committed baseline: the M7 refresh sweep over the Band 4 corpus AND
//! the demo scenes — 1,792,902 / 1,792,926 / 1,792,950 samples at
//! ε ∈ {1e-6, 1e-9, 1e-12}, 233 distinct predicate names, generated by
//! `K_SWEEP_PREFIX=m7-eps- scripts/k_probe_sweep.sh docs/k-report-data
//! --gzip`. The M4 baseline these thresholds were first cut against
//! (`m4-eps-*`, 2,562,157/row) and the M5 snapshot (`m5-eps-*`,
//! 1,758,387/row) stay committed as the durable record.
//!
//! The row counts are NOT equal across ε any more (+24/row): the
//! ε-coupled family below samples more often at tighter ε (K-REPORT
//! Finding M5-1). Everything else is geometry, not tolerance.
//!
//! These rows are a SNAPSHOT at the head where they were cut, not a
//! mirror of main — same contract as `m4-*` and `m5-*`. A fresh sweep
//! at a later main can therefore disagree with the baseline's ROSTER in
//! both directions, and has: it can carry predicates the baseline never
//! saw (`path_junction_turn`, +293 samples/row, every |m| ≥ 2.5 m), and
//! since #661 pooled the six `bool_sector_*` / `split_sector_*` names
//! into `sector_{arm,reflex,straight}` it also DROPS six the baseline
//! still lists — 233 committed here, 231 at today's main. Neither
//! direction reaches this lint, which lints the fresh rows it was
//! handed and never compares them to the committed files; the thresholds
//! below are the only thing the baseline supplies. The baseline is
//! re-cut when the DISTRIBUTION moves — a new floor, a filled gap, an
//! ε-coupled family — not on every merge and not on a rename.
//!
//! The ε-INDEPENDENT distribution is still sharply bimodal (full
//! histogram: docs/K-REPORT.md, M7 addendum) — 1,348,461 ambient
//! definite samples, the same COUNT at all three rows:
//!
//! - zero-classified cluster: |m| ≤ 5.329e-15 (worst: `pm_census_ee_span`
//!   on demo/az) — unmoved since M4;
//! - definite cluster: |m| ≥ 4.7965e-5 (worst: `volume_backstop` on
//!   corpus/die_pips and corpus/die_composed — the pip cavities' volume
//!   slack metered as a mean boundary displacement, a real 48 µm
//!   quantity);
//! - the ~10.0-decade gap between them is EMPTY once the ε-coupled
//!   family is set aside: 0 indeterminate, 0 invalid, 0 samples.
//!
//! One carve-out on "ε-independent", stated because the classification
//! is otherwise clean enough to mislead: every predicate but
//! `props_quad_converged` reproduces its minimum BIT-IDENTICALLY at all
//! three rows EXCEPT `props_quad_face_extent` (12 ambient definite
//! samples/row, 8 of them differing; minima 4.0245003e-1 /
//! 4.0256189e-1 / 4.0256210e-1). That one is ε-DEPENDENT but not
//! ε-proportional — it is the CONVERGED quadrature's face extent, so it
//! converges toward a fixed ~0.4025621 m as ε tightens instead of
//! tracking ε. It therefore belongs under the metre rules, NOT in
//! [`EPS_COUPLED_PREDICATES`], and at 0.40 m (4 decades above the
//! floor, outside the gap) the population count, its P0, and the gap's
//! emptiness are identical whichever way it is classified.
//!
//! [`BASELINE_FLOOR_MARGIN`] is the **0th percentile** of that
//! ε-independent definite population (observed minimum 4.7965e-5,
//! rounded down to 4.0e-5 — 16.6% of headroom).
//! Percentile choice rationale (spec: "REPORT the percentile choice"),
//! re-argued against the M7 distribution: P0.001 = 1.4916e-4 already
//! strands the die/die_pips/die_composed backstop margins; P0.01 =
//! 3.8393e-3 strands the whole `volume_backstop` family plus
//! `pm_census_ee_gap` (M4's old floor) and `split_bisector_side`;
//! P0.1 = 2.4e-2 and P1 = 6.25e-2 strand most of the corpus's
//! millimetre-scale work. Any P > 0 is permanent noise with no added
//! signal, because the 10-decade empty gap makes the population edge
//! itself the maximally informative threshold: a NEW margin below the
//! floor sits in the no-man's land between honest coincidence and
//! honest feature — exactly the #99 class (margin 2.315e-6: in-band at
//! ε = 1e-6, and below this floor at EVERY supported ε row, with 1.2
//! decades to spare).
//!
//! Headroom is wider than M4's ~11% on purpose: M4's floor sample was a
//! rigid feature gap, while `volume_backstop`'s margin is ΔV/(A+A) — a
//! smeared quantity that moves with how fine the model's detail is
//! relative to its surface area, so it deserves a wider skirt.
//!
//! The floor compares the margin in its own units (meters for the
//! geometric predicates; the few radian·arm-metered angular margins
//! share the numeric floor — their baseline minima sit far above it).
//!
//! # The ε-coupled families (rule 4)
//!
//! [`EPS_COUPLED_PREDICATES`] lists the predicates whose recorded
//! margin is a headroom against an ε-SCALED target rather than a
//! model-scale distance. Today that is exactly one:
//! `props_quad_converged`, the adaptive-quadrature stopping test — it
//! records `1024·ε − width`, so its margin shrinks with ε BY
//! CONSTRUCTION (baseline minima 8.3952e-4 / 1.6467e-7 / 3.3595e-10 at
//! 1e-6 / 1e-9 / 1e-12).
//!
//! No fixed metre floor can be both clean at 1e-12 and informative, so
//! this family is taken out from under rule (3). It is taken out from
//! under rule (2) as well, and that is the honest half of the ruling:
//! its entire operating range is (0, 1024·ε] = (0, 102.4·Kε] at the
//! ratified K = 10, so "within 10² of Kε" is its PERMANENT state and
//! carries no information — rule (2) applied to it is a tautology, not
//! a finding. Muting it is not an option either, so rule (4) is rule
//! (2) RECALIBRATED to the family's own scale: flag when the headroom
//! falls below [`EPS_COUPLED_FLOOR_RATIO`] · ε = 15·Kε, the bottom ~15%
//! of the range. That is a real fragility statement — the stopping
//! round cleared the target by so little that at the interval scalar
//! the enclosure could straddle and escalate.
//!
//! [`EPS_COUPLED_FLOOR_RATIO`] = 1.5e2 is the P0 of the baseline's own
//! |m|/ε population (minimum 164.674, at demo/tiltedcut on the 1e-9
//! row; the other rows sit at 839.524 and 335.953) rounded down with
//! 8.9% of headroom. Its semantics DIFFER from the metre floor's and
//! the difference is worth naming: this is a calibrated proximity
//! rule on a BOUNDED statistic, not the edge of an empty gap. The
//! quadrature loop stops at the first round whose width clears the
//! target and widths fall ~8× per round, so the headroom has no
//! structural lower bound — a face whose width lands just under target
//! WILL trip rule (4). That is the intended signal, not a false
//! positive: it is the same decision fragility rule (2) exists to name,
//! measured where this family actually lives.
//!
//! Membership is an explicit allow-list, never inferred. A NEW
//! ε-coupled predicate is not on it, so it stays under rules (2) and
//! (3) and flags loudly until someone rules on it — the fail-loud
//! direction.
//!
//! **That promise is carried by the TIGHT rows, and it is worth being
//! precise about which** (review NOTE-2, pinned in
//! `tests/review_probes.rs`): at 1e-9 and 1e-12 a not-yet-ruled
//! ε-coupled family's margins scale down with ε, land far below
//! [`BASELINE_FLOOR_MARGIN`], and trip rules (2) and (3) together. At
//! the 1e-6 row they do not — rule (2)'s cap below leaves most of such
//! a family's operating range silent there (a mid-range 5e-4 headroom
//! passes clean). The sweep always runs all three rows, so CI always
//! has the rows where the promise binds; a single-row run at 1e-6 would
//! not, and should not be trusted to surface a new ε-coupled family.
//!
//! # Rule (2)'s discrimination floor
//!
//! Rules (2)-above and (3) are two thresholds on the SAME quantity — a
//! definite ε-independent margin — one in band units (`10²·Kε`), one in
//! metres (the corpus's measured floor). Rule (2) says something rule
//! (3) does not only while `10²·Kε < BASELINE_FLOOR_MARGIN`: there it
//! catches margins that are BOTH far below the corpus's honest-feature
//! floor AND near the band, which is strictly stronger. When the
//! inequality flips, rule (2) degenerates into a second, UNCALIBRATED
//! floor sitting above the calibrated one, and it then flags exactly
//! the corpus's own known fine-feature population — including the very
//! samples the floor was cut from.
//!
//! At the ratified K = 10 that flip happens at the loosest supported
//! row: `10²·Kε = 1e-3 m` at ε = 1e-6, 25× above the M7 floor of
//! 4.0e-5 m. Measured on the M7 baseline, the uncapped rule prints 54
//! flags there — every one a `volume_backstop` sample between 4.80e-5
//! and 9.50e-4 m on corpus/die, corpus/die_pips, corpus/die_composed,
//! demo/die and demo/projectbox_cutaway, all of them ε-independent, all
//! of them above the floor, none of them moving — and 0 flags at 1e-9
//! and 1e-12, where the rule still discriminates.
//!
//! So rule (2)-above is capped at [`BASELINE_FLOOR_MARGIN`]
//! ([`proximity_above_threshold`]). This is a statement about the
//! rule's discriminating power, not a family exemption: every margin
//! below the floor still answers to BOTH rules, rule (1) still catches
//! any sample that actually escalates, and the cap is inert at both
//! rows where rule (2) is the stronger statement. What is genuinely
//! true at ε = 1e-6 — that this corpus's finest honest features sit
//! less than a decade above the escalation band, i.e. that 1e-6 is a
//! loose ε for a sub-millimetre corpus — is a fact about the ε choice,
//! not about any one sample. The CLI therefore never suppresses it
//! silently: it prints the cap and both numbers on every file where it
//! binds ([`Scan::proximity_capped`]).

/// Ratio rules apply only to ambient (ε-scale) bands; the exact
/// tie-break bands the kernel also records are 5e-324 / 1e-100 —
/// dozens of decades below any supported ε (1e-6 … 1e-12).
pub const AMBIENT_BAND_MIN: f64 = 1e-13;

/// "Within 10^2 of the band": the spec's proximity factor (D3).
pub const PROXIMITY_FACTOR: f64 = 1e2;

/// The baseline distribution's bottom edge (provenance in the module
/// docs — the M7 baseline's smallest ε-INDEPENDENT definite margin
/// 4.7965e-5, P0, rounded down to 4.0e-5 so the baseline itself lints
/// clean with 16.6% of headroom).
pub const BASELINE_FLOOR_MARGIN: f64 = 4.0e-5;

/// The ε-coupled families: predicates whose recorded margin is a
/// headroom against an ε-scaled target, not a model-scale distance.
/// Exempt from rules (2) and (3), watched by rule (4) instead — the
/// argument is in the module docs ("The ε-coupled families"). An
/// explicit allow-list on purpose: a new ε-coupled predicate is NOT on
/// it and keeps flagging under the metre rules until someone rules.
pub const EPS_COUPLED_PREDICATES: [&str; 1] = ["props_quad_converged"];

/// Rule (4)'s floor for [`EPS_COUPLED_PREDICATES`], in units of ε:
/// P0 of the baseline's |m|/ε population (minimum 164.674), rounded
/// down to 1.5e2 = 15·Kε with 8.9% of headroom.
///
/// **"P0" here does NOT carry [`BASELINE_FLOOR_MARGIN`]'s rigor, and
/// the difference is deliberate to state** (review NOTE-1): the metre
/// floor's P0 is the edge of a 1,348,461-sample population separated
/// from the zero cluster by an empty 10-decade gap, so a sample below
/// it is a genuine no-man's-land event. This one is the MINIMUM OF 108
/// DRAWS (12/36/60 per row) of a statistic bounded above by 1024·ε with
/// NO structural lower bound — the quadrature loop stops at the first
/// round whose width clears the target, so the leftover headroom is
/// whatever that round happened to land on. 8.9% of headroom on such a
/// minimum is weak protection by construction, and a future sweep may
/// legitimately dip under 150·ε and fire the row with nothing wrong.
/// That is the rule working (the margin really is close to the band),
/// not the constant being mis-cut. So this is the threshold whose
/// firing is likeliest to be threshold staleness rather than a
/// distribution change: it wants re-derivation from a larger
/// population, not a re-rounding — and never a geometry tweak (the
/// CLI's recourse (1), `main.rs`).
pub const EPS_COUPLED_FLOOR_RATIO: f64 = 1.5e2;

/// Whether `predicate` is one of the [`EPS_COUPLED_PREDICATES`].
#[must_use]
pub fn is_eps_coupled(predicate: &str) -> bool {
    EPS_COUPLED_PREDICATES.contains(&predicate)
}

/// Rule (2)'s definite-side threshold at a row whose escalation
/// threshold is `band_escalate`: `10²·Kε`, capped at
/// [`BASELINE_FLOOR_MARGIN`] where the raw ratio stops discriminating
/// (module docs, "Rule (2)'s discrimination floor").
#[must_use]
pub fn proximity_above_threshold(band_escalate: f64) -> f64 {
    (band_escalate * PROXIMITY_FACTOR).min(BASELINE_FLOOR_MARGIN)
}

/// Why a sample was flagged.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    /// Outcome `indeterminate`: the margin landed INSIDE the band.
    InBand,
    /// Outcome `invalid`: poisoned margin.
    Invalid,
    /// Definite margin within [`PROXIMITY_FACTOR`] of `band_escalate`.
    NearBandAbove,
    /// Zero-classified margin within [`PROXIMITY_FACTOR`] below
    /// `band_zero`.
    NearBandBelow,
    /// Definite margin below [`BASELINE_FLOOR_MARGIN`].
    BelowBaselineFloor,
    /// An [`EPS_COUPLED_PREDICATES`] margin below
    /// [`EPS_COUPLED_FLOOR_RATIO`] · ε.
    BelowEpsCoupledFloor,
}

impl core::fmt::Display for Reason {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let s = match self {
            Reason::InBand => "IN the ambiguity band (indeterminate outcome)",
            Reason::Invalid => "invalid (poisoned) margin",
            Reason::NearBandAbove => "definite within 10^2 of the escalation threshold",
            Reason::NearBandBelow => "zero-classified within 10^2 of the coincidence threshold",
            Reason::BelowBaselineFloor => "definite below the baseline distribution's floor (4e-5)",
            Reason::BelowEpsCoupledFloor => {
                "ε-coupled headroom below the ε-relative floor (1.5e2·ε)"
            }
        };
        f.write_str(s)
    }
}

/// One flagged CSV row.
#[derive(Debug, Clone)]
pub struct Flag {
    /// 1-based line number in the input.
    pub line: usize,
    pub shape: String,
    pub predicate: String,
    pub margin: f64,
    pub band_zero: f64,
    pub reasons: Vec<Reason>,
}

/// The result of linting one CSV.
#[derive(Debug)]
pub struct Scan {
    /// Samples considered (every non-header, non-empty line).
    pub scanned: usize,
    pub flags: Vec<Flag>,
    /// `Some((10²·Kε, floor))` when this file's ambient rows are loose
    /// enough that rule (2)'s definite arm was capped at the baseline
    /// floor. The CLI PRINTS this — the cap is never silent (module
    /// docs, "Rule (2)'s discrimination floor").
    pub proximity_capped: Option<(f64, f64)>,
}

/// The sweep's CSV header: the column order this file's rules are
/// stated against, and the only header [`lint_csv`] accepts.
const EXPECTED_HEADER: &str = "shape,predicate,margin,band_zero,band_escalate,outcome";

/// What a numeric column of the sweep may say.
///
/// **A reading the lint cannot read is not a sample that passed.** Every
/// rule in [`lint_sample`] is an `m < t` or `m > t` comparison, so a
/// `NaN` margin makes all of them false and the row scores CLEAN while
/// still counting in [`Scan::scanned`]; a `NaN` `band_zero` misses the
/// `band_zero >= AMBIENT_BAND_MIN` guard on every arm and answers to no
/// rule at all. So a value outside its column's policy is refused as
/// harness breakage, for the same reason the `outcome` allow-list beside
/// it already gives (review MIN-2): the instrument's answer to an
/// unreadable measurement must not be its own pass value.
///
/// The recorder is the authority for both policies. `k_stats::record`
/// writes the margin `Decide for f64` classified together with the
/// thresholds of the `Band` it was classified against, and `Band::new`
/// refuses a threshold that is not finite and strictly positive — so a
/// zero or negative band is drift, not a loose band.
///
/// **`Band::new`'s third invariant is not one of these**, and cannot be:
/// `BandError::Empty` is `zero < escalate`, a relation between two
/// columns that each admit alone. A row inverting them was classified
/// against a band the recorder could not have built, and rule (2)'s two
/// arms would then sit on opposite sides of a band that does not exist —
/// `m < EPS_COUPLED_FLOOR_RATIO * band_zero` for the ε-coupled
/// predicates and `m < proximity_above_threshold(band_escalate)` for the
/// rest — making the verdict incoherent rather than wrong in a stated
/// direction. [`lint_csv`] checks it where the two admissions meet.
#[derive(Clone, Copy, Debug)]
enum Admissible {
    /// A classified margin: any FINITE value, of either sign — a margin
    /// is a signed length and the corpus records both signs and exact
    /// zeros. The two non-finite spellings are admitted only against
    /// the outcomes that produce them: `NaN` is the poison
    /// `Decide for f64` reports as `invalid`, and ±∞ is documented
    /// there as maximally definite, so it can only accompany a definite
    /// outcome. A pairing the recorder could not have written is drift,
    /// and the one this rule exists for is `NaN` on an outcome whose
    /// every comparison it makes false.
    Margin,
    /// A band threshold: finite and strictly positive, which is
    /// `Band::new`'s own contract.
    BandThreshold,
}

impl Admissible {
    /// Whether `v` is a reading of this kind of column on a row whose
    /// recorded outcome is `outcome` (already checked against the
    /// outcome allow-list by [`lint_csv`]).
    fn admits(self, v: f64, outcome: &str) -> bool {
        match self {
            Self::Margin => {
                if v.is_nan() {
                    outcome == "invalid"
                } else if v.is_infinite() {
                    matches!(outcome, "positive" | "negative")
                } else {
                    true
                }
            }
            Self::BandThreshold => v.is_finite() && v > 0.0,
        }
    }

    /// What this column may say, for the harness message.
    fn expects(self) -> &'static str {
        match self {
            Self::Margin => {
                "a margin: finite, or NaN on an `invalid` outcome, or ±inf on a definite one"
            }
            Self::BandThreshold => "a band threshold, finite and above zero",
        }
    }
}

/// The float block — every column [`lint_sample`] compares against, in
/// [`EXPECTED_HEADER`]'s order, with what each may say. One table
/// rather than three hand-written checks so that the block the parser
/// polices and the block the header declares can be compared to each
/// other, which this module's tests do: a fourth float column added
/// without an entry here would otherwise reach the rules unpoliced.
const FLOAT_COLUMNS: [(&str, Admissible); 3] = [
    ("margin", Admissible::Margin),
    ("band_zero", Admissible::BandThreshold),
    ("band_escalate", Admissible::BandThreshold),
];

/// A malformed input line: HARNESS BREAKAGE — the lint could not run.
/// Findings fail the CI row too, but in their own voice and with their
/// own exit code (`main.rs`); the two are never blurred.
#[derive(Debug)]
pub struct ParseError {
    pub line: usize,
    pub text: String,
}

/// Lint verdict for one parsed sample; empty when the sample is
/// clean. Exposed for the litmus test, which synthesizes the #99
/// datum against every supported ε row's band.
///
/// `predicate` selects the rule set: the [`EPS_COUPLED_PREDICATES`]
/// answer to rule (4) instead of rules (2) and (3) — module docs.
#[must_use]
pub fn lint_sample(
    predicate: &str,
    margin: f64,
    band_zero: f64,
    band_escalate: f64,
    outcome: &str,
) -> Vec<Reason> {
    let mut reasons = Vec::new();
    let m = margin.abs();
    match outcome {
        "indeterminate" => reasons.push(Reason::InBand),
        "invalid" => reasons.push(Reason::Invalid),
        "zero" if band_zero >= AMBIENT_BAND_MIN => {
            // Coincidence proximity is the same question in the same
            // units for every family: a zero classification is a
            // decision against ε itself, ε-coupled or not.
            if m > band_zero / PROXIMITY_FACTOR {
                reasons.push(Reason::NearBandBelow);
            }
        }
        "positive" | "negative" if band_zero >= AMBIENT_BAND_MIN => {
            if is_eps_coupled(predicate) {
                if m < EPS_COUPLED_FLOOR_RATIO * band_zero {
                    reasons.push(Reason::BelowEpsCoupledFloor);
                }
            } else {
                if m < proximity_above_threshold(band_escalate) {
                    reasons.push(Reason::NearBandAbove);
                }
                if m < BASELINE_FLOOR_MARGIN {
                    reasons.push(Reason::BelowBaselineFloor);
                }
            }
        }
        _ => {}
    }
    reasons
}

/// Lints a whole CSV (the sweep's format:
/// `shape,predicate,margin,band_zero,band_escalate,outcome`).
///
/// # Errors
///
/// The first malformed line — bad column count, unparseable float, an
/// UNKNOWN outcome string, or a float outside its column's policy
/// (`Admissible`) — harness breakage. A FINDING is never an `Err`: it
/// comes back in [`Scan::flags`], and the CLI turns it into its own
/// failure voice.
pub fn lint_csv(text: &str) -> Result<Scan, ParseError> {
    let mut flags = Vec::new();
    let mut scanned = 0usize;
    let mut proximity_capped = None;
    for (i, line) in text.lines().enumerate() {
        if i == 0 {
            if line != EXPECTED_HEADER {
                return Err(ParseError {
                    line: 1,
                    text: line.to_string(),
                });
            }
            continue;
        }
        if line.is_empty() {
            continue;
        }
        let err = || ParseError {
            line: i + 1,
            text: line.to_string(),
        };
        let mut it = line.split(',');
        let (Some(shape), Some(pred), Some(m), Some(bz), Some(be), Some(out), None) = (
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
            it.next(),
        ) else {
            return Err(err());
        };
        // An unknown outcome string is harness breakage, exactly like
        // a malformed float: scoring it silently CLEAN would let a
        // sweep-format drift disarm the whole lint (review MIN-2). It
        // is checked FIRST because the margin's policy is stated
        // against it (`Admissible::Margin`).
        if !matches!(
            out,
            "zero" | "positive" | "negative" | "indeterminate" | "invalid"
        ) {
            return Err(err());
        }
        // An unreadable measurement is harness breakage too, and for
        // the same reason — see `Admissible`.
        // The column index carries BOTH halves of the policy — the name
        // the message reports and the rule it was refused by — so the
        // two cannot drift apart per column.
        let admit = |field: &str, col: usize| -> Result<f64, ParseError> {
            let (name, kind) = FLOAT_COLUMNS[col];
            let v: f64 = field.parse().map_err(|_| err())?;
            if kind.admits(v, out) {
                Ok(v)
            } else {
                Err(ParseError {
                    line: i + 1,
                    text: format!(
                        "{name} = {v:e} is not {} (sweep drift?): {line}",
                        kind.expects()
                    ),
                })
            }
        };
        let margin = admit(m, 0)?;
        let band_zero = admit(bz, 1)?;
        let band_escalate = admit(be, 2)?;
        // The band property no per-column policy can state, because it
        // is a RELATION between two columns that each admit alone.
        if band_zero >= band_escalate {
            return Err(ParseError {
                line: i + 1,
                text: format!(
                    "band_zero = {band_zero:e} must be strictly below                      band_escalate = {band_escalate:e} (the ambiguity band is a                      nonempty open interval; sweep drift?): {line}"
                ),
            });
        }
        scanned += 1;
        // Record (once) that rule (2)-above is running capped on this
        // file's ambient rows, so the CLI can say so out loud.
        if band_zero >= AMBIENT_BAND_MIN && proximity_capped.is_none() {
            let raw = band_escalate * PROXIMITY_FACTOR;
            if raw > BASELINE_FLOOR_MARGIN {
                proximity_capped = Some((raw, BASELINE_FLOOR_MARGIN));
            }
        }
        let reasons = lint_sample(pred, margin, band_zero, band_escalate, out);
        if !reasons.is_empty() {
            flags.push(Flag {
                line: i + 1,
                shape: shape.to_string(),
                predicate: pred.to_string(),
                margin,
                band_zero,
                reasons,
            });
        }
    }
    Ok(Scan {
        scanned,
        flags,
        proximity_capped,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_definite_and_zero_pass() {
        // Baseline-shaped samples: definite far above the band, zero at
        // machine noise.
        assert!(lint_sample("p", 2.0, 1e-9, 1e-8, "positive").is_empty());
        assert!(lint_sample("p", -2.0, 1e-9, 1e-8, "negative").is_empty());
        assert!(lint_sample("p", 1e-16, 1e-9, 1e-8, "zero").is_empty());
    }

    #[test]
    fn in_band_and_invalid_always_flag() {
        assert_eq!(
            lint_sample("p", 2.3e-6, 1e-6, 1e-5, "indeterminate"),
            vec![Reason::InBand]
        );
        assert_eq!(
            lint_sample("p", f64::NAN, 1e-9, 1e-8, "invalid"),
            vec![Reason::Invalid]
        );
        // The gate does NOT exempt outcome-based flags.
        assert_eq!(
            lint_sample("p", 0.0, 5e-324, 1e-323, "invalid"),
            vec![Reason::Invalid]
        );
        // …nor does the ε-coupled allow-list: rule (4) replaces the
        // two RATIO rules only, never the outcome rule.
        assert_eq!(
            lint_sample("props_quad_converged", 5e-9, 1e-9, 1e-8, "indeterminate"),
            vec![Reason::InBand]
        );
    }

    #[test]
    fn proximity_flags_both_sides_of_the_band() {
        // Definite 1.5 decades above Kε: flagged (and it is also below
        // the baseline floor).
        assert_eq!(
            lint_sample("p", 3e-7, 1e-9, 1e-8, "positive"),
            vec![Reason::NearBandAbove, Reason::BelowBaselineFloor]
        );
        // Zero half a decade below ε: flagged.
        assert_eq!(
            lint_sample("p", 3e-10, 1e-9, 1e-8, "zero"),
            vec![Reason::NearBandBelow]
        );
    }

    #[test]
    fn floor_flags_the_gap_population() {
        // A margin in the bimodal gap, definite at 1e-9 — exactly the
        // #99 class. (Not near the band: 2.315e-6 > 10²·Kε = 1e-6.)
        assert_eq!(
            lint_sample("p", 2.315e-6, 1e-9, 1e-8, "positive"),
            vec![Reason::BelowBaselineFloor]
        );
        // At the M7 baseline's observed ε-independent minimum
        // (`volume_backstop`, corpus/die_pips): clean at the two rows
        // where the band leaves room — the floor is P0 rounded DOWN.
        assert!(lint_sample("volume_backstop", 4.7965e-5, 1e-9, 1e-8, "positive").is_empty());
        assert!(lint_sample("volume_backstop", 4.7965e-5, 1e-12, 1e-11, "positive").is_empty());
        // M4's old floor sample is now ~1.6 decades ABOVE the floor:
        // clean, and no longer the bottom of the distribution.
        assert!(lint_sample("pm_census_ee_gap", 1.689e-3, 1e-6, 1e-5, "positive").is_empty());
        // Just under the floor still flags.
        assert_eq!(
            lint_sample("p", 3.9e-5, 1e-12, 1e-11, "positive"),
            vec![Reason::BelowBaselineFloor]
        );
    }

    #[test]
    fn eps_coupled_family_answers_to_the_eps_relative_floor_only() {
        assert!(is_eps_coupled("props_quad_converged"));
        assert!(!is_eps_coupled("volume_backstop"));
        // The three baseline minima of `props_quad_converged`
        // (8.3952e-4 / 1.6467e-7 / 3.3595e-10 at 1e-6 / 1e-9 / 1e-12):
        // all CLEAN under rule (4).
        for (m, zero, esc) in [
            (8.3952e-4, 1e-6, 1e-5),
            (1.6467e-7, 1e-9, 1e-8),
            (3.3595e-10, 1e-12, 1e-11),
        ] {
            assert!(
                lint_sample("props_quad_converged", m, zero, esc, "positive").is_empty(),
                "baseline ε-coupled minimum {m:e} must lint clean at ε={zero:e}"
            );
        }
        // The two tight rows are what makes the exemption load-bearing:
        // the SAME margins under the metre rules flag on both counts.
        for (m, zero, esc) in [(1.6467e-7, 1e-9, 1e-8), (3.3595e-10, 1e-12, 1e-11)] {
            assert_eq!(
                lint_sample("volume_backstop", m, zero, esc, "positive"),
                vec![Reason::NearBandAbove, Reason::BelowBaselineFloor],
                "the SAME margin under the metre rules must flag"
            );
        }
        // Below 1.5e2·ε: rule (4) fires, and only rule (4).
        assert_eq!(
            lint_sample("props_quad_converged", 1.4e-7, 1e-9, 1e-8, "positive"),
            vec![Reason::BelowEpsCoupledFloor]
        );
        // The convergence target itself (1024·ε) is the family's
        // ceiling and sits just above rule (2)'s 10²·Kε — the
        // tautology rule (4) replaces.
        assert!(lint_sample("props_quad_converged", 1.024e-9, 1e-12, 1e-11, "positive").is_empty());
    }

    #[test]
    fn rule_two_above_is_capped_at_the_baseline_floor() {
        // Where the raw ratio still discriminates (10²·Kε below the
        // floor), the cap is inert.
        assert!((proximity_above_threshold(1e-8) - 1e-6).abs() < 1e-20);
        assert!((proximity_above_threshold(1e-11) - 1e-9).abs() < 1e-24);
        // At ε = 1e-6 the raw ratio is 1e-3 — 25× the floor — so it caps.
        assert!((proximity_above_threshold(1e-5) - BASELINE_FLOOR_MARGIN).abs() < 1e-20);
        // The M7 baseline's ε-independent floor sample (`volume_backstop`,
        // corpus/die_pips) at the 1e-6 row: honest feature, above the
        // floor, no longer flagged by the degenerate ratio.
        assert!(lint_sample("volume_backstop", 4.7965e-5, 1e-6, 1e-5, "positive").is_empty());
        // …but a margin BELOW the floor still gets BOTH rules at that
        // row — the cap is not an exemption.
        assert_eq!(
            lint_sample("volume_backstop", 3.9e-5, 1e-6, 1e-5, "positive"),
            vec![Reason::NearBandAbove, Reason::BelowBaselineFloor]
        );
        // …and rule (1) is untouched wherever a sample actually
        // escalates.
        assert_eq!(
            lint_sample("volume_backstop", 5e-6, 1e-6, 1e-5, "indeterminate"),
            vec![Reason::InBand]
        );
    }

    #[test]
    fn tight_rows_report_no_cap() {
        // Review NOTE-3: the inert half of the cap contract, pinned at
        // the same level the binding half is. A file whose ambient rows
        // are all tight (10²·Kε below the floor) must report NO cap —
        // rule (2) ran unmodified there.
        let csv = "shape,predicate,margin,band_zero,band_escalate,outcome\n\
                   demo/x,p1,2e0,1e-9,1e-8,positive\n\
                   demo/x,p2,2e0,1e-12,1e-11,positive\n\
                   demo/x,p3,0e0,5e-324,1e-323,zero\n";
        let scan = lint_csv(csv).expect("valid csv");
        assert_eq!(scan.scanned, 3);
        assert!(scan.flags.is_empty());
        assert_eq!(
            scan.proximity_capped, None,
            "the cap must stay inert — and stay SILENT — at rows where \
             rule (2) still discriminates"
        );
    }

    #[test]
    fn exact_tie_break_bands_are_exempt_from_ratio_rules() {
        // canonical_order-style sample: tiny coordinate delta against
        // the 5e-324 band — an order decision, not a coincidence one.
        assert!(lint_sample("p", 1e-4, 5e-324, 1e-323, "positive").is_empty());
        // segment_straightness-style exact zero.
        assert!(lint_sample("p", 0.0, 1e-100, 1e-99, "zero").is_empty());
    }

    #[test]
    fn csv_parses_flags_and_refuses_malformed() {
        let csv = "shape,predicate,margin,band_zero,band_escalate,outcome\n\
                   demo/x,p1,2e0,1e-9,1e-8,positive\n\
                   demo/x,p2,2.315e-6,1e-6,9.999999999999999e-6,indeterminate\n";
        let scan = lint_csv(csv).expect("valid csv");
        let (scanned, flags) = (scan.scanned, scan.flags);
        assert_eq!(scanned, 2);
        // The 1e-6 row's band is loose enough that rule (2)-above ran
        // capped — and the scan says so.
        assert_eq!(
            scan.proximity_capped,
            Some((
                9.999999999999999e-6 * PROXIMITY_FACTOR,
                BASELINE_FLOOR_MARGIN
            ))
        );
        assert_eq!(flags.len(), 1);
        assert_eq!(flags[0].predicate, "p2");
        assert_eq!(flags[0].reasons, vec![Reason::InBand]);
        assert!(lint_csv("bad header\n").is_err());
        // MIN-2 pin: a typo'd outcome must FAIL the row, not score
        // silently clean.
        assert!(
            lint_csv(
                "shape,predicate,margin,band_zero,band_escalate,outcome\nx,y,2e0,1e-9,1e-8,positve\n"
            )
            .is_err()
        );
        assert!(
            lint_csv(
                "shape,predicate,margin,band_zero,band_escalate,outcome\nx,y,notafloat,1,1,zero\n"
            )
            .is_err()
        );
    }

    /// One row, with each float column settable.
    fn row(margin: &str, band_zero: &str, band_escalate: &str, outcome: &str) -> String {
        format!("{EXPECTED_HEADER}\ndemo/x,p,{margin},{band_zero},{band_escalate},{outcome}\n")
    }

    /// The block the parser polices is the header's own, bracketed on
    /// both sides: a column inserted into the float run would slide
    /// every reading under the wrong policy, and the drifting header
    /// this file already refuses is the same failure one step earlier.
    #[test]
    fn the_policed_block_is_the_headers_float_block() {
        /// Where the float block starts in [`EXPECTED_HEADER`]. Only
        /// the bracket test needs it — `lint_csv` destructures the row
        /// positionally, so the offset it uses IS this header's.
        const FLOAT_FIRST: usize = 2;
        let cols: Vec<&str> = EXPECTED_HEADER.split(',').collect();
        assert_eq!(
            cols[FLOAT_FIRST - 1],
            "predicate",
            "the block starts too late"
        );
        for (k, (name, _)) in FLOAT_COLUMNS.iter().enumerate() {
            assert_eq!(cols[FLOAT_FIRST + k], *name, "column {k}");
        }
        assert_eq!(
            cols[FLOAT_FIRST + FLOAT_COLUMNS.len()],
            "outcome",
            "the block ends too early"
        );
        assert_eq!(
            cols.len(),
            FLOAT_FIRST + FLOAT_COLUMNS.len() + 1,
            "a float column past `outcome` would reach the rules unpoliced"
        );
    }

    /// The question this parser exists to answer. Every rule is an
    /// `m < t` or `m > t` comparison, so an unreadable value resolves
    /// every rule to false and the row scores CLEAN — the instrument's
    /// failure mode would be its own pass condition. Each of these rows
    /// scored clean before it was refused.
    ///
    /// The expectations are written out rather than derived from
    /// [`FLOAT_COLUMNS`]: a test that reads the policy it is checking
    /// asserts nothing.
    #[test]
    fn every_float_column_refuses_the_readings_that_would_score_a_row_clean() {
        // `0e0` is the value that discriminates a band threshold's
        // "above zero" from a mere "non-negative": relax
        // `Admissible::BandThreshold` to `v >= 0.0` and this loop reds
        // rather than only some fixture breaking.
        for bad in ["0e0", "-1e0", "inf", "-inf", "NaN"] {
            assert!(
                lint_csv(&row("2e0", bad, "1e-8", "positive")).is_err(),
                "band_zero = {bad} must be harness breakage"
            );
            assert!(
                lint_csv(&row("2e0", "1e-9", bad, "positive")).is_err(),
                "band_escalate = {bad} must be harness breakage"
            );
        }
        // A margin is a SIGNED length: both signs and an exact zero are
        // readings, and the corpus records all three.
        for good in ["2e0", "-2e0", "0e0"] {
            assert!(
                lint_csv(&row(good, "1e-9", "1e-8", "positive")).is_ok(),
                "margin = {good} is a reading"
            );
        }
        // The two non-finite spellings belong to the outcomes that
        // produce them and to no others: `NaN` is the poison reported
        // as `invalid`, ±∞ is maximally definite.
        const OUTCOMES: [&str; 5] = ["zero", "positive", "negative", "indeterminate", "invalid"];
        const NAN_ADMITTED: [bool; 5] = [false, false, false, false, true];
        const INF_ADMITTED: [bool; 5] = [false, true, true, false, false];
        for (k, outcome) in OUTCOMES.iter().enumerate() {
            assert_eq!(
                lint_csv(&row("NaN", "1e-9", "1e-8", outcome)).is_ok(),
                NAN_ADMITTED[k],
                "margin NaN at outcome {outcome}"
            );
            for inf in ["inf", "-inf"] {
                assert_eq!(
                    lint_csv(&row(inf, "1e-9", "1e-8", outcome)).is_ok(),
                    INF_ADMITTED[k],
                    "margin {inf} at outcome {outcome}"
                );
            }
        }
        // And the one row NaN belongs on is still a FINDING, not an
        // error: rule (1) names it.
        let scan = lint_csv(&row("NaN", "1e-9", "1e-8", "invalid")).expect("poison is a reading");
        assert_eq!(scan.scanned, 1);
        assert_eq!(scan.flags[0].reasons, vec![Reason::Invalid]);
    }

    /// `Band::new`'s third invariant, which the per-column admissions
    /// structurally cannot carry: each threshold is checked alone and
    /// the PAIR never was, so an inverted or degenerate band parsed,
    /// counted in [`Scan::scanned`], and was linted against a band the
    /// recorder could not have built.
    #[test]
    fn an_empty_band_is_harness_breakage_however_admissible_its_columns() {
        // Both columns are finite and strictly positive on every row
        // here, so `Admissible::BandThreshold` admits all of them —
        // which is the point.
        for (bz, be) in [
            ("1e-8", "1e-9"),     // inverted
            ("1e-9", "1e-9"),     // equal: `zero >= escalate` is closed
            ("1e-323", "5e-324"), // the ambient tie-break band, inverted
        ] {
            let e =
                lint_csv(&row("2e0", bz, be, "positive")).expect_err("an empty band is not a band");
            assert_eq!(e.line, 2);
            assert!(e.text.contains("band_zero"), "{}", e.text);
            assert!(e.text.contains("strictly below"), "{}", e.text);
        }
        // A hairline band is REPRESENTABLY empty and mathematically
        // nonempty, and `Band::new` accepts it — so this lint must too,
        // or the instrument is stricter than the thing it measures.
        let t = 1e-9f64;
        assert!(
            lint_csv(&row(
                "2e0",
                "1e-9",
                &format!("{:e}", t.next_up()),
                "positive"
            ))
            .is_ok(),
            "a hairline band is a band"
        );
    }

    /// The refusal names the column and the policy it broke, not just
    /// the line — the harness voice `lint_csv` already owns.
    #[test]
    fn the_refusal_names_the_column_that_broke_its_policy() {
        let e = lint_csv(&row("2e0", "-1e-9", "1e-8", "positive")).expect_err("negative band");
        assert_eq!(e.line, 2);
        assert!(e.text.contains("band_zero"), "{}", e.text);
        assert!(e.text.contains("above zero"), "{}", e.text);
    }
}
