# Per-fixture structural probe, run by scripts/check_step.sh with
# $STEP_FILE set (the generic sidecar hook: any <fixture>.probe.py next
# to a .step is executed after the count/volume checks). Exit 0 iff
# every assertion holds.
#
# WHY THIS FIXTURE NEEDS ONE, AND WHY IT PARSES THE FILE ITSELF.
#
# The generic checks are counts and a volume, and neither can see an
# orientation error here. `filleted_die` is the unit cube [0, 1]^3, so
# three of its six support planes pass THROUGH THE ORIGIN, and flipping
# a face whose plane contains the origin leaves the divergence-theorem
# volume integral unchanged: the volume assertion is blind to exactly
# the failure a fillet assembly is most likely to make. The FreeCAD
# import's own orientation guarantee comes from `isValid()`
# (`BRepCheck_Analyzer`), not from the volume line.
#
# So this probe states the structural facts directly, and it reads the
# Part 21 text rather than an imported shape on purpose: the counts
# below are the KERNEL's (48 edges, 24 arcs), while OCC splits the
# periodic corner-arc carriers at their seams and reports 56. Nothing
# here needs a CAD kernel — stdlib only, so it also runs under a plain
# `python3 <probe>` with STEP_FILE set.
#
# THE STANDING CLAIM IT GUARDS. The byte-golden fixture cannot be its
# own evidence: it is regenerated by the same change that needs
# checking, so "it matches the committed bytes" says nothing about
# whether the new bytes describe a correctly oriented solid. These four
# checks are fixture-independent of the writer's emission order and of
# which entity numbering it chose, and they are what actually
# establishes that the file describes the rounded cube:
#
#   1. every face's outward normal points away from the body centroid;
#   2. the shell is closed and consistently oriented — every edge curve
#      is used exactly twice, once in each direction;
#   3. every planar support's boundary winds CCW about that face's own
#      outward normal, with the closed-form signed area;
#   4. every corner arc sweeps exactly 90 degrees in its own
#      parametric direction.
#
# Together they pin orientation, closure and the blend's geometry
# without reference to any previous revision of the file.
import math
import os
import re
import sys

L = 1.0  # the cube's side, metres
R = 0.12  # the blend radius, metres
TOL = 1e-12

text = open(os.environ["STEP_FILE"]).read()
data = text.split("DATA;", 1)[1].split("ENDSEC;", 1)[0]

ENT = {}
for m in re.finditer(r"#(\d+)\s*=\s*([A-Z_0-9]+)\s*\((.*?)\)\s*;", data, re.S):
    ENT[int(m.group(1))] = (m.group(2), m.group(3))


def args(text):
    """Split one entity's argument list at top-level commas."""
    out, depth, cur = [], 0, ""
    for ch in text:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    out.append(cur.strip())
    return out


def ref(token):
    return int(token.strip().lstrip("#"))


def refs(token):
    return [ref(t) for t in args(token.strip()[1:-1]) if t.strip()]


def flag(token):
    return token.strip() == ".T."


def triple(key):
    """A CARTESIAN_POINT's or DIRECTION's three reals."""
    body = re.search(r"\(([^()]*)\)\s*$", ENT[key][1].strip()).group(1)
    return tuple(float(x) for x in body.split(","))


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def scale(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def norm(a):
    return math.sqrt(dot(a, a))


def unit(a):
    return scale(a, 1.0 / norm(a))


def placement(key):
    """AXIS2_PLACEMENT_3D -> (location, axis, ref_direction)."""
    a = args(ENT[key][1])
    loc = triple(ref(a[1]))
    axis = unit(triple(ref(a[2])))
    rdir = unit(triple(ref(a[3])))
    # Gram-Schmidt: the record's ref_direction need not be exactly
    # perpendicular, and the placement's x-axis is its projection.
    rdir = unit(sub(rdir, scale(axis, dot(rdir, axis))))
    return loc, axis, rdir


failures = []

# ---- Index the shell: faces, their bounds, their oriented edges. ----
faces = [k for k, (t, _) in ENT.items() if t == "ADVANCED_FACE"]
edge_uses = {}  # edge_curve key -> list of effective directions
face_records = []
for fk in sorted(faces):
    fa = args(ENT[fk][1])
    bounds = refs(fa[1])
    surface = ref(fa[2])
    same_sense = flag(fa[3])
    loops = []
    for bk in bounds:
        ba = args(ENT[bk][1])
        loop = ref(ba[1])
        bound_ok = flag(ba[2])
        chain = []
        for oek in refs(args(ENT[loop][1])[1]):
            oa = args(ENT[oek][1])
            ec = ref(oa[3])
            # The traversal direction as seen from the face's OUTWARD
            # side: the oriented edge's own flag, folded through the
            # bound's flag and the face's sense. Three reversals
            # compose by XOR.
            reversed_ = (not flag(oa[4])) ^ (not bound_ok) ^ (not same_sense)
            effective = not reversed_
            chain.append((ec, effective))
            edge_uses.setdefault(ec, []).append(effective)
        loops.append(chain)
    face_records.append((fk, surface, same_sense, loops))

if len(face_records) != 26:
    failures.append(f"expected 26 faces, got {len(face_records)}")
if len(edge_uses) != 48:
    failures.append(f"expected 48 distinct edge curves, got {len(edge_uses)}")

# ---- The body centroid, for the outward test. ----
# The rounded cube is symmetric, so the mean of its vertex points IS
# its centre; it only has to be a point strictly inside for check 1.
verts = [triple(ref(args(ENT[k][1])[1])) for k, (t, _) in ENT.items() if t == "VERTEX_POINT"]
centre = scale((sum(p[0] for p in verts), sum(p[1] for p in verts), sum(p[2] for p in verts)), 1.0 / len(verts))

# ---- Check 1: every face's outward normal points away from centre. ----
# ---- Check 3: every planar support winds CCW about its own normal. ----
planar_areas = []
outward_violations = []
arc_edges = []
for fk, sk, same_sense, loops in face_records:
    kind, sargs = ENT[sk][0], args(ENT[sk][1])
    loc, axis, rdir = placement(ref(sargs[1]))
    sign = 1.0 if same_sense else -1.0
    ring = [
        triple(ref(args(ENT[ref(args(ENT[ec][1])[1 if fwd else 2])][1])[1]))
        for ec, fwd in loops[0]
    ]
    if kind == "PLANE":
        n = scale(axis, sign)
        point = loc
        # Signed area of the boundary polygon about the face's own
        # outward normal (Stokes on the planar loop).
        acc = (0.0, 0.0, 0.0)
        for i, p in enumerate(ring):
            acc = add(acc, cross(p, ring[(i + 1) % len(ring)]))
        planar_areas.append(0.5 * dot(acc, n))
    elif kind == "CYLINDRICAL_SURFACE":
        radius = float(sargs[2])
        q = scale((sum(p[0] for p in ring), sum(p[1] for p in ring), sum(p[2] for p in ring)), 1.0 / len(ring))
        d = sub(q, loc)
        radial = unit(sub(d, scale(axis, dot(d, axis))))
        n = scale(radial, sign)
        point = add(add(loc, scale(axis, dot(d, axis))), scale(radial, radius))
    elif kind == "SPHERICAL_SURFACE":
        radius = float(sargs[2])
        q = scale((sum(p[0] for p in ring), sum(p[1] for p in ring), sum(p[2] for p in ring)), 1.0 / len(ring))
        radial = unit(sub(q, loc))
        n = scale(radial, sign)
        point = add(loc, scale(radial, radius))
    else:
        failures.append(f"face #{fk}: unexpected surface {kind}")
        continue
    if dot(sub(point, centre), n) <= 0.0:
        outward_violations.append(fk)
    for ec, _ in loops[0]:
        if ENT[ref(args(ENT[ec][1])[3])][0] == "CIRCLE":
            arc_edges.append(ec)

if outward_violations:
    failures.append(f"faces whose normal points INWARD: {sorted(outward_violations)}")
if len(planar_areas) != 6:
    failures.append(f"expected 6 planar supports, got {len(planar_areas)}")
# The shrunk support is the source square inset by R on every side.
want_area = (L - 2.0 * R) ** 2
for a in planar_areas:
    if abs(a - want_area) > 1e-12:
        failures.append(f"planar support signed area {a!r} is not {want_area!r} (CCW about its outward normal)")

# ---- Check 2: closed, consistently oriented shell. ----
bad_pairs = [(k, v) for k, v in edge_uses.items() if sorted(v) != [False, True]]
if bad_pairs:
    failures.append(
        f"{len(bad_pairs)} edge curve(s) not used exactly twice in opposite directions: "
        f"{sorted(k for k, _ in bad_pairs)[:8]}"
    )

# ---- Check 4: every corner arc sweeps exactly 90 degrees. ----
arcs = sorted(set(arc_edges))
if len(arcs) != 24:
    failures.append(f"expected 24 circle-carried corner arcs, got {len(arcs)}")
worst = 0.0
for ec in arcs:
    ea = args(ENT[ec][1])
    p0 = triple(ref(args(ENT[ref(ea[1])][1])[1]))
    p1 = triple(ref(args(ENT[ref(ea[2])][1])[1]))
    circle = ref(ea[3])
    if not flag(ea[4]):
        p0, p1 = p1, p0
    loc, axis, rdir = placement(ref(args(ENT[circle][1])[1]))
    ydir = cross(axis, rdir)

    # B023 on `loc`/`ydir`/`rdir`: bugbear flags a closure over a loop
    # variable because such a closure usually outlives the iteration that
    # bound it. This one does not — `angle` is defined, called twice on the
    # next line, and rebound on the next pass; there is no later call to
    # read a stale binding.
    def angle(p):
        d = sub(p, loc)  # noqa: B023
        return math.atan2(dot(d, ydir), dot(d, rdir))  # noqa: B023

    sweep = (angle(p1) - angle(p0)) % (2.0 * math.pi)
    worst = max(worst, abs(sweep - math.pi / 2.0))
if worst > 1e-12:
    failures.append(f"a corner arc sweeps {math.degrees(worst):.6e} degrees away from 90")

if failures:
    for f in failures:
        print("  FAIL:", f)
    sys.exit(1)
print(
    f"  die probe OK: {len(face_records)} faces, 0 inward normals; {len(edge_uses)} edge "
    f"curves each used twice in opposite directions; {len(planar_areas)} planar supports "
    f"CCW at signed area {want_area!r}; {len(arcs)} arcs within {worst:.3e} rad of a "
    f"quarter turn"
)
