#!/usr/bin/env bash
# K-telemetry probe sweep (M4 PR 8b, spec D3): collects the complete
# per-predicate margin distribution of the Band 4 corpus AND the demo
# tour scenes at the recording scalar `Probe`, one process per ε
# (`Tolerance` is a OnceLock), and merges the two dumps into one CSV
# per ε row (M2 file convention: shape,predicate,margin,band_zero,
# band_escalate,outcome; shapes namespaced corpus/<doc> and
# demo/<scene>).
#
# Usage:
#   scripts/k_probe_sweep.sh <outdir> [--gzip]
#   K_SWEEP_PREFIX=m7-eps- scripts/k_probe_sweep.sh <outdir> --gzip
#
# Writes <outdir>/<prefix><ε>.csv (plus .gz and no plain CSV when
# --gzip); the prefix defaults to the milestone-neutral `k-eps-` and is
# overridden by K_SWEEP_PREFIX. It used to be hard-coded `m4-eps-`,
# which is why the M5 baseline had to be renamed by hand on commit (a
# deviation the M5 addendum reported and left standing); the committed
# baselines are milestone-stamped, so the stamp is now the script's own
# argument instead of a manual rename.
#
# The committed baseline in docs/k-report-data/ was generated by
# exactly this script with --gzip (raw rows are 162-203 MB; the gzipped
# baseline is the durable record — same rows, same columns). The ci
# `k-lint` job runs the same sweep into a scratch dir and lints the
# fresh rows against the thresholds pinned in tools/k-lint.
set -euo pipefail
cd "$(dirname "$0")/.."
root=$(pwd)

out_arg=${1:?usage: k_probe_sweep.sh <outdir> [--gzip]}
mkdir -p "$out_arg"
outdir=$(cd "$out_arg" && pwd)
gz=${2:-}
prefix=${K_SWEEP_PREFIX:-k-eps-}

for eps in 1e-6 1e-9 1e-12; do
  corpus="$outdir/.corpus-$eps.csv"
  demos="$outdir/.demos-$eps.csv"
  merged="$outdir/$prefix$eps.csv"
  # `--features probe` on both halves: the recording scalar
  # `geom_core::k_stats::Probe` is opt-in (see geom-core's manifest — it is
  # a `Real` instantiation, so it monomorphizes every generic-over-`Real`
  # body, and this sweep is its only consumer). Without the feature the
  # corpus filter below matches nothing and the tour's `k-probe` mode
  # refuses loudly; either way this script is the thing that must pass it.
  echo "=== k-probe sweep @ eps=$eps (corpus) ==="
  CAD_TOLERANCE_EPS=$eps CAD_K_REPORT_OUT="$corpus" \
    cargo test -p editor-core --features probe --test all -- --ignored --nocapture m4_pr8_k_probe::
  echo "=== k-probe sweep @ eps=$eps (demo scenes) ==="
  (cd "$root/demos/tour" && CAD_TOLERANCE_EPS=$eps cargo run --features probe -- k-probe "$demos")
  # One header, then both bodies — corpus first, demos second.
  cat "$corpus" > "$merged"
  tail -n +2 "$demos" >> "$merged"
  rm "$corpus" "$demos"
  if [ "$gz" = "--gzip" ]; then
    gzip -9 -f "$merged"
    echo "wrote $merged.gz"
  else
    echo "wrote $merged"
  fi
done
