#!/usr/bin/env bash
# K-telemetry probe sweep (M4 PR 8b, spec D3): collects the complete
# per-predicate margin distribution of the Band 4 corpus AND the demo
# tour scenes at the recording scalar `Probe`, one process per ε
# (`Tolerance` is a OnceLock), and merges the two dumps into one CSV
# per ε row (M2 file convention: shape,predicate,margin,band_zero,
# band_escalate,outcome; shapes namespaced corpus/<doc> and
# demo/<scene>).
#
# Usage:
#   scripts/k_probe_sweep.sh <outdir> [--gzip]
#   K_SWEEP_PREFIX=m7-eps- scripts/k_probe_sweep.sh <outdir> --gzip
#
# Writes <outdir>/<prefix><ε>.csv (plus .gz and no plain CSV when
# --gzip); the prefix defaults to the milestone-neutral `k-eps-` and is
# overridden by K_SWEEP_PREFIX. It used to be hard-coded `m4-eps-`,
# which is why the M5 baseline had to be renamed by hand on commit (a
# deviation the M5 addendum reported and left standing); the committed
# baselines are milestone-stamped, so the stamp is now the script's own
# argument instead of a manual rename.
#
# The committed baseline in docs/k-report-data/ was generated by
# exactly this script with --gzip (raw rows are 162-203 MB; the gzipped
# baseline is the durable record — same rows, same columns). The ci
# `k-lint` job runs the same sweep into a scratch dir and lints the
# fresh rows against the thresholds pinned in tools/k-lint.
#
# THE M2 CORPUS RIDES BESIDE, NOT INSIDE. `crates/sweep/tests/k_report.rs`
# is the M2-era instrument over the ten M2 acceptance shapes. It is dumped
# to `<outdir>/m2/<prefix><ε>.csv` and is NOT merged into the linted CSV:
# what k-lint gates is a distribution whose thresholds were argued over
# the Band 4 corpus and the tour scenes, and folding ten more shapes into
# it would move the gate's subject matter, which is a geometry
# conversation and not a coverage one. What running it here buys is that
# the harness is EXECUTED on every building merge — a type-check cannot
# see a panic — and that the command re-cutting the M2 baseline is this
# script rather than a runbook line nothing runs.
set -euo pipefail
cd "$(dirname "$0")/.."
root=$(pwd)

out_arg=${1:?usage: k_probe_sweep.sh <outdir> [--gzip]}
mkdir -p "$out_arg"
outdir=$(cd "$out_arg" && pwd)
gz=${2:-}
prefix=${K_SWEEP_PREFIX:-k-eps-}

mkdir -p "$outdir/m2"

# WHAT ACTUALLY RAN, one row per invocation:
# `<mode><TAB><crate><TAB><module><TAB><passed>`. The mode is the
# SELECTION — `--ignored` or the default — because the two run disjoint
# halves of a suite and confusing them is the whole of D84: every
# document put `editor-core` on the executed side because this script
# names it with `-p`, while the only thing it ran there was the one
# `#[ignore]`d dump. `probe-suite-census.sh --check-executed` reads this
# file at the end and floors it. The count comes from the test runner's
# own `N passed` line, never from what a filter could have matched: a
# filter matching a suite whose tests carry no `#[ignore]` selects the
# module and runs none of it, so reachability and execution are
# different questions and only the second one is worth a floor.
ran="$outdir/.executed.tsv"
: > "$ran"
export RAN_TALLY="$ran"
record_ran() {
  printf '%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" >> "$RAN_TALLY"
}

# `test result: ok. N passed` — the runner's own count of tests that
# EXECUTED, which is the only number that can tell a covered suite from
# a selected and inert one.
passed_count() {
  sed -n 's/^test result: ok\. \([0-9]\{1,\}\) passed.*/\1/p' "$1" | head -1
}

# A NAME FILTER THAT MATCHES NOTHING EXITS 0. Every harness below is
# selected by `--ignored <module>::` against an aggregated `--test all`
# binary, so nothing about the selection is checked by cargo: a renamed
# module, a dropped `#[ignore]`, or a suite that fell out of its crate's
# `tests/all.rs` all produce a green run over zero rows and an empty CSV.
# So the row count and the dump are both asserted here — this is the only
# place that can tell the difference between "clean" and "ran nothing".
run_dump() {
  local eps=$1 label=$2 pkg=$3 filter=$4 out=$5 log passed
  log=$(mktemp)
  echo "=== k-probe sweep @ eps=$eps ($label) ==="
  CAD_TOLERANCE_EPS=$eps CAD_K_REPORT_OUT="$out" \
    cargo test -p "$pkg" --features probe --test all -- \
      --ignored --nocapture "$filter" | tee "$log"
  passed=$(passed_count "$log")
  rm -f "$log"
  record_ran ignored "$pkg" "${filter%%::*}" "${passed:-0}"
  if [ "${passed:-0}" -lt 1 ]; then
    echo "ERROR: \`$filter\` matched no test in $pkg — the sweep recorded nothing and would have exited 0. Check the module name and its \`#[ignore]\`." >&2
    exit 1
  fi
  # `wc -l < missing` prints NOTHING, and `[ "" -lt 2 ]` errors — which
  # inside an `if` condition is exempt from `set -e`, so the guard would
  # take the false branch and pass in exactly the case it names. Default
  # the count instead.
  if [ "$(wc -l < "$out" 2>/dev/null || echo 0)" -lt 2 ]; then
    echo "ERROR: $label wrote no sample rows to $out — the harness ran but recorded no margins." >&2
    exit 1
  fi
}

# THE PROBE LANE'S PRECONDITIONS, and they are not part of the sweep.
# Each of these is a plain `#[test]` — no `#[ignore]` — asserting that
# the recording scalar is a WRAPPER and not a second arithmetic: the
# corpus evaluates green at `Probe`, and a corpus document replays there
# with bit-identical decisions. Every margin row the loop below writes
# rests on that, which is why they run FIRST.
#
# ONCE, AND OUTSIDE THE eps LOOP, deliberately. Both assert bit-identity
# against the f64 lane, not a margin distribution, so there is nothing
# per-eps about either claim; sweeping them would state three times over
# something neither test says. The loop was simply where the other
# invocations were.
#
# THE SELECTION IS THE DEFAULT ONE, which is the point. `run_dump` above
# passes `--ignored` and therefore runs ONLY `#[ignore]`d tests; that is
# how both of these — one of them in a module the sweep already named —
# went from being written to never having executed, without anyone
# choosing it.
run_plain() {
  local label=$1 pkg=$2 module=$3 log passed
  log=$(mktemp)
  echo "=== probe-lane precondition ($label) ==="
  cargo test -p "$pkg" --features probe --test all -- "$module::" | tee "$log"
  passed=$(passed_count "$log")
  rm -f "$log"
  record_ran plain "$pkg" "$module" "${passed:-0}"
  if [ "${passed:-0}" -lt 1 ]; then
    echo "ERROR: \`$module::\` selected no runnable test in $pkg — the precondition asserted nothing and would have exited 0. Check the module name, and that its tests are NOT \`#[ignore]\`d." >&2
    exit 1
  fi
}

run_plain "corpus green at Probe" editor-core m4_pr8_k_probe
run_plain "corpus replay at Probe" editor-core m5_pr5_corpus_probe

for eps in 1e-6 1e-9 1e-12; do
  corpus="$outdir/.corpus-$eps.csv"
  demos="$outdir/.demos-$eps.csv"
  merged="$outdir/$prefix$eps.csv"
  m2="$outdir/m2/$prefix$eps.csv"
  # `--features probe` on every half: the recording scalar
  # `geom_core::k_stats::Probe` is opt-in (see geom-core's manifest — it is
  # a `Real` instantiation, so it monomorphizes every generic-over-`Real`
  # body, and this sweep is its only consumer). Without the feature the
  # corpus filters match nothing and the tour's `k-probe` mode refuses
  # loudly; either way this script is the thing that must pass it.
  run_dump "$eps" corpus editor-core m4_pr8_k_probe:: "$corpus"
  # The M2-era instrument. `sweep` sets `autotests = false`, so there is
  # no `--test k_report` target and selection is by module prefix.
  run_dump "$eps" "M2 corpus" sweep k_report:: "$m2"
  echo "=== k-probe sweep @ eps=$eps (demo scenes) ==="
  (cd "$root/demos/tour" && CAD_TOLERANCE_EPS=$eps cargo run --features probe -- k-probe "$demos")
  # One header, then both bodies — corpus first, demos second.
  cat "$corpus" > "$merged"
  tail -n +2 "$demos" >> "$merged"
  rm "$corpus" "$demos"
  if [ "$gz" = "--gzip" ]; then
    gzip -9 -f "$merged" "$m2"
    echo "wrote $merged.gz and $m2.gz"
  else
    echo "wrote $merged and $m2"
  fi
done

# THE FLOOR ON WHAT RAN. Every invocation above recorded its own passed
# count; this is what turns a sweep that selected everything and executed
# nothing into a failure, and it is the only place with the evidence to
# do it.
scripts/gates/probe-suite-census.sh --check-executed < "$ran"
